// ╔══════════════════════════════════════════════════════════════╗
// ║  DONNÉES MENUS — mis à jour chaque mardi par cowork          ║
// ║  Ne modifier que semaine1 et semaine2                        ║
// ╚══════════════════════════════════════════════════════════════╝

// ── DONNÉES SEMAINE 1 ──────────────────────────────────────────
const semaine1=[
  // LUNDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr banane myrtilles flocons amandes',kcal:296,p:19,g:41,l:7,portions:'2 adultes',ings:['Skyr 150g','Banane 70g','Myrtilles 40g','Flocons avoine 20g','Amandes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les amandes.','Couper la banane en rondelles.','Disposer les myrtilles et déguster.'],note:'Myrtilles d\'automne (surgelées acceptées).'},
    {moment:'Déjeuner',nom:'Blanc poulet riz basmati épinards champignons',kcal:444,p:33,g:62,l:7,portions:'2 adultes',ings:['Blanc poulet 100g','Riz basmati 75g','Épinards frais 70g','Champignons 50g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter les champignons émincés, cuire 4 min.','Ajouter les épinards, cuire 2 min et servir avec le riz.'],note:'Épinards et champignons d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt nature banane flocons amandes',kcal:265,p:11,g:31,l:12,portions:'2 adultes',ings:['Yaourt nature 150g','Banane 60g','Flocons avoine 15g','Amandes 12g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les amandes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et rapide.'},
    {moment:'Dîner',nom:'Lentilles vertes courgette poivron tomates concassées riz complet',kcal:506,p:22,g:86,l:7,portions:'4 pers.',ings:['Riz complet 55g','Lentilles vertes 70g','Courgette 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Faire revenir la courgette et le poivron dans l\'huile 5 min.','Ajouter les lentilles vertes et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr banane myrtilles flocons amandes',kcal:383,p:25,g:53,l:9,portions:'2 adultes',ings:['Skyr 194g','Banane 90g','Myrtilles 52g','Flocons avoine 26g','Amandes 13g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les amandes.','Couper la banane en rondelles.','Disposer les myrtilles et déguster.'],note:'Myrtilles d\'automne (surgelées acceptées).'},
    {moment:'Déjeuner',nom:'Blanc poulet riz basmati épinards champignons',kcal:553,p:41,g:78,l:8,portions:'2 adultes',ings:['Blanc poulet 125g','Riz basmati 94g','Épinards frais 88g','Champignons 62g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter les champignons émincés, cuire 4 min.','Ajouter les épinards, cuire 2 min et servir avec le riz.'],note:'Épinards et champignons d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt nature banane flocons amandes',kcal:324,p:14,g:38,l:14,portions:'2 adultes',ings:['Yaourt nature 183g','Banane 73g','Flocons avoine 18g','Amandes 15g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les amandes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et rapide.'},
    {moment:'Dîner',nom:'Lentilles vertes courgette poivron tomates concassées riz complet',kcal:506,p:22,g:86,l:7,portions:'4 pers.',ings:['Riz complet 55g','Lentilles vertes 70g','Courgette 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Faire revenir la courgette et le poivron dans l\'huile 5 min.','Ajouter les lentilles vertes et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // MARDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine banane beurre de cacahuète lait végétal',kcal:341,p:11,g:51,l:11,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 80g','Banane 60g','Beurre cacahuète 12g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la banane coupée en rondelles.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Petit-déjeuner énergétique.'},
    {moment:'Déjeuner',nom:'Maquereau fumé riz complet brocoli tomates citron',kcal:460,p:29,g:55,l:13,portions:'2 adultes',ings:['Maquereau fumé en boîte 90g','Riz complet 65g','Brocoli 70g','Tomates 60g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Émietter le maquereau fumé.','Assembler riz + maquereau + brocoli + tomates, filet de citron.'],note:'Poisson gras riche en oméga-3, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr banane noisettes',kcal:165,p:13,g:17,l:5,portions:'2 adultes',ings:['Skyr 130g','Banane 50g','Noisettes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les noisettes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et économique.'},
    {moment:'Dîner',nom:'Pois chiches courgette aubergine tomates concassées riz basmati',kcal:480,p:18,g:82,l:8,portions:'4 pers.',ings:['Riz basmati 50g','Pois chiches 65g','Courgette 60g','Aubergine 50g','Tomates concassées 60g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir la courgette et l\'aubergine dans l\'huile 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine banane beurre de cacahuète lait végétal',kcal:435,p:14,g:66,l:14,portions:'2 adultes',ings:['Flocons avoine 64g','Lait végétal 103g','Banane 77g','Beurre cacahuète 15g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la banane coupée en rondelles.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Petit-déjeuner énergétique.'},
    {moment:'Déjeuner',nom:'Maquereau fumé riz complet brocoli tomates citron',kcal:573,p:36,g:69,l:16,portions:'2 adultes',ings:['Maquereau fumé en boîte 112g','Riz complet 81g','Brocoli 88g','Tomates 75g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Émietter le maquereau fumé.','Assembler riz + maquereau + brocoli + tomates, filet de citron.'],note:'Poisson gras riche en oméga-3, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr banane noisettes',kcal:203,p:16,g:21,l:6,portions:'2 adultes',ings:['Skyr 159g','Banane 61g','Noisettes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les noisettes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et économique.'},
    {moment:'Dîner',nom:'Pois chiches courgette aubergine tomates concassées riz basmati',kcal:480,p:18,g:82,l:8,portions:'4 pers.',ings:['Riz basmati 50g','Pois chiches 65g','Courgette 60g','Aubergine 50g','Tomates concassées 60g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir la courgette et l\'aubergine dans l\'huile 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // MERCREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine kiwi skyr amandes lait végétal',kcal:412,p:20,g:63,l:9,portions:'2 adultes',ings:['Flocons avoine 75g','Skyr 90g','Lait végétal 50g','Kiwi 70g','Amandes 5g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper le kiwi et incorporer.','Parsemer les amandes.','Déguster froid.'],note:'Préparer la veille. Kiwi de saison.'},
    {moment:'Déjeuner',nom:'Boeuf maigre riz basmati poivron oignon',kcal:479,p:26,g:66,l:12,portions:'2 adultes',ings:['Boeuf maigre 90g','Riz basmati 75g','Poivron rouge 70g','Oignon 40g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Émincer l\'oignon, faire revenir avec le poivron dans l\'huile 5 min.','Poêler le boeuf maigre en lanières 5 min.','Mélanger avec le riz et servir.'],note:'Poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse kiwi miel amandes',kcal:241,p:11,g:19,l:14,portions:'2 adultes',ings:['Petit suisse 130g','Kiwi 60g','Miel 5g','Amandes 8g'],steps:['Couper le kiwi en dés.','Verser sur le petit suisse.','Parsemer les amandes et arroser de miel.'],note:'Kiwi de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade riz complet courgette poivron tomates oignon',kcal:348,p:17,g:36,l:15,portions:'4 pers.',ings:['Oeufs 2 pièces','Riz complet 35g','Courgette 50g','Poivron rouge 50g','Tomates 60g','Oignon 30g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Émincer l\'oignon, faire revenir avec le poivron et la courgette dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs, verser sur les légumes, cuire à feu doux 4 min et servir avec le riz.'],note:'Pipérade complète, 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine kiwi skyr amandes lait végétal',kcal:530,p:26,g:82,l:12,portions:'2 adultes',ings:['Flocons avoine 97g','Skyr 116g','Lait végétal 64g','Kiwi 90g','Amandes 6g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper le kiwi et incorporer.','Parsemer les amandes.','Déguster froid.'],note:'Préparer la veille. Kiwi de saison.'},
    {moment:'Déjeuner',nom:'Boeuf maigre riz basmati poivron oignon',kcal:597,p:32,g:82,l:15,portions:'2 adultes',ings:['Boeuf maigre 112g','Riz basmati 94g','Poivron rouge 88g','Oignon 50g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Émincer l\'oignon, faire revenir avec le poivron dans l\'huile 5 min.','Poêler le boeuf maigre en lanières 5 min.','Mélanger avec le riz et servir.'],note:'Poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse kiwi miel amandes',kcal:296,p:14,g:23,l:17,portions:'2 adultes',ings:['Petit suisse 159g','Kiwi 73g','Miel 6g','Amandes 10g'],steps:['Couper le kiwi en dés.','Verser sur le petit suisse.','Parsemer les amandes et arroser de miel.'],note:'Kiwi de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade riz complet courgette poivron tomates oignon',kcal:348,p:17,g:36,l:15,portions:'4 pers.',ings:['Oeufs 2 pièces','Riz complet 35g','Courgette 50g','Poivron rouge 50g','Tomates 60g','Oignon 30g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Émincer l\'oignon, faire revenir avec le poivron et la courgette dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs, verser sur les légumes, cuire à feu doux 4 min et servir avec le riz.'],note:'Pipérade complète, 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // JEUDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature banane flocons noix',kcal:355,p:14,g:50,l:13,portions:'2 adultes',ings:['Yaourt nature 150g','Banane 60g','Flocons avoine 45g','Noix 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Couper la banane en rondelles et déguster frais.'],note:'Petit-déjeuner simple et économique.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz complet épinards tomates',kcal:463,p:26,g:57,l:14,portions:'2 adultes',ings:['Cuisses poulet désossées 95g','Riz complet 70g','Épinards frais 80g','Tomates 60g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les épinards, cuire 3 min.','Ajouter les tomates, cuire 2 min et servir sur le riz.'],note:'Épinards d\'automne de saison.'},
    {moment:'Collation',nom:'Fromage blanc poire miel amandes',kcal:153,p:11,g:16,l:4,portions:'2 adultes',ings:['Fromage blanc maigre 140g','Poire 50g','Miel 5g','Amandes 8g'],steps:['Verser le fromage blanc dans un bol.','Couper la poire en dés.','Parsemer les amandes et arroser de miel.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Haricots rouges potiron poivron tomates concassées riz complet',kcal:515,p:21,g:89,l:8,portions:'4 pers.',ings:['Riz complet 55g','Haricots rouges 70g','Potiron 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Faire revenir le potiron et le poivron dans l\'huile 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature banane flocons noix',kcal:456,p:18,g:64,l:16,portions:'2 adultes',ings:['Yaourt nature 194g','Banane 77g','Flocons avoine 58g','Noix 10g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Couper la banane en rondelles et déguster frais.'],note:'Petit-déjeuner simple et économique.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz complet épinards tomates',kcal:578,p:33,g:72,l:17,portions:'2 adultes',ings:['Cuisses poulet désossées 119g','Riz complet 88g','Épinards frais 100g','Tomates 75g','Huile olive 6g'],steps:['Cuire le riz complet 20 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les épinards, cuire 3 min.','Ajouter les tomates, cuire 2 min et servir sur le riz.'],note:'Épinards d\'automne de saison.'},
    {moment:'Collation',nom:'Fromage blanc poire miel amandes',kcal:188,p:14,g:20,l:5,portions:'2 adultes',ings:['Fromage blanc maigre 171g','Poire 61g','Miel 6g','Amandes 10g'],steps:['Verser le fromage blanc dans un bol.','Couper la poire en dés.','Parsemer les amandes et arroser de miel.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Haricots rouges potiron poivron tomates concassées riz complet',kcal:515,p:21,g:89,l:8,portions:'4 pers.',ings:['Riz complet 55g','Haricots rouges 70g','Potiron 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Faire revenir le potiron et le poivron dans l\'huile 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // VENDREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine framboises beurre de cacahuète lait végétal',kcal:349,p:12,g:50,l:12,portions:'2 adultes',ings:['Flocons avoine 60g','Lait végétal 80g','Framboises 50g','Beurre cacahuète 12g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer les framboises.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Thon riz basmati brocoli carotte citron',kcal:432,p:34,g:59,l:7,portions:'2 adultes',ings:['Thon en boîte 100g','Riz basmati 65g','Brocoli 70g','Carotte 50g','Huile olive 5g','Citron herbes fraîches 1g'],steps:['Cuire le riz basmati 12 min.','Cuire le brocoli vapeur 7 min.','Égoutter le thon et râper la carotte.','Assembler riz + thon + brocoli + carotte, filet d\'huile et de citron.'],note:'Poisson maigre, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr banane amandes',kcal:182,p:14,g:20,l:5,portions:'2 adultes',ings:['Skyr 130g','Banane 60g','Amandes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et économique.'},
    {moment:'Dîner',nom:'Lentilles corail épinards champignons tomates concassées riz basmati',kcal:514,p:25,g:89,l:6,portions:'4 pers.',ings:['Riz basmati 55g','Lentilles corail 70g','Épinards frais 60g','Champignons 60g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons dans l\'huile 5 min.','Ajouter les épinards, les lentilles corail et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine framboises beurre de cacahuète lait végétal',kcal:446,p:15,g:64,l:16,portions:'2 adultes',ings:['Flocons avoine 77g','Lait végétal 103g','Framboises 64g','Beurre cacahuète 15g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer les framboises.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Thon riz basmati brocoli carotte citron',kcal:537,p:42,g:74,l:8,portions:'2 adultes',ings:['Thon en boîte 125g','Riz basmati 81g','Brocoli 88g','Carotte 62g','Huile olive 6g','Citron herbes fraîches 1g'],steps:['Cuire le riz basmati 12 min.','Cuire le brocoli vapeur 7 min.','Égoutter le thon et râper la carotte.','Assembler riz + thon + brocoli + carotte, filet d\'huile et de citron.'],note:'Poisson maigre, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr banane amandes',kcal:220,p:18,g:24,l:6,portions:'2 adultes',ings:['Skyr 159g','Banane 73g','Amandes 12g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et économique.'},
    {moment:'Dîner',nom:'Lentilles corail épinards champignons tomates concassées riz basmati',kcal:514,p:25,g:89,l:6,portions:'4 pers.',ings:['Riz basmati 55g','Lentilles corail 70g','Épinards frais 60g','Champignons 60g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons dans l\'huile 5 min.','Ajouter les épinards, les lentilles corail et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // SAMEDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine myrtilles miel yaourt amandes famille',kcal:407,p:18,g:50,l:15,portions:'4 pers.',ings:['Flocons avoine mixés 45g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 70g','Myrtilles 30g','Miel 5g','Amandes 10g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf et le lait végétal en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, myrtilles, amandes et miel.'],note:'Les enfants adorent ! Myrtilles surgelées acceptées.'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé poivron aubergine riz complet',kcal:459,p:18,g:64,l:14,portions:'4 pers.',ings:['Boeuf haché maigre 56g','Riz complet 75g','Poivron rouge 90g','Aubergine 60g','Huile olive 6g'],steps:['Cuire le riz complet 20 min.','Couper le poivron et l\'aubergine.','Griller les légumes à la poêle 8 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec riz et légumes.'],note:'Plat du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc framboises myrtilles miel amandes famille',kcal:164,p:12,g:16,l:6,portions:'4 pers.',ings:['Fromage blanc maigre 130g','Framboises 30g','Myrtilles 30g','Miel 5g','Amandes 10g'],steps:['Verser le fromage blanc dans un bol.','Disposer les framboises et les myrtilles.','Parsemer les amandes et arroser de miel.'],note:'Fruits rouges surgelés acceptés toute l\'année.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte champignons tomates riz basmati',kcal:510,p:27,g:68,l:14,portions:'4 pers.',ings:['Cuisses poulet désossées 95g','Riz basmati 75g','Carotte 60g','Champignons 60g','Tomates concassées 70g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et champignons, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine myrtilles miel yaourt amandes famille',kcal:407,p:18,g:50,l:15,portions:'4 pers.',ings:['Flocons avoine mixés 45g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 70g','Myrtilles 30g','Miel 5g','Amandes 10g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf et le lait végétal en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, myrtilles, amandes et miel.'],note:'Les enfants adorent ! Myrtilles surgelées acceptées.'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé poivron aubergine riz complet',kcal:459,p:18,g:64,l:14,portions:'4 pers.',ings:['Boeuf haché maigre 56g','Riz complet 75g','Poivron rouge 90g','Aubergine 60g','Huile olive 6g'],steps:['Cuire le riz complet 20 min.','Couper le poivron et l\'aubergine.','Griller les légumes à la poêle 8 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec riz et légumes.'],note:'Plat du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc framboises myrtilles miel amandes famille',kcal:164,p:12,g:16,l:6,portions:'4 pers.',ings:['Fromage blanc maigre 130g','Framboises 30g','Myrtilles 30g','Miel 5g','Amandes 10g'],steps:['Verser le fromage blanc dans un bol.','Disposer les framboises et les myrtilles.','Parsemer les amandes et arroser de miel.'],note:'Fruits rouges surgelés acceptés toute l\'année.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte champignons tomates riz basmati',kcal:510,p:27,g:68,l:14,portions:'4 pers.',ings:['Cuisses poulet désossées 95g','Riz basmati 75g','Carotte 60g','Champignons 60g','Tomates concassées 70g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et champignons, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // DIMANCHE
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr banane myrtilles noix famille',kcal:412,p:18,g:58,l:13,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 70g','Banane 50g','Myrtilles 25g','Flocons avoine 45g','Noix 12g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la banane en rondelles.','Parsemer les flocons et les noix.','Disposer les myrtilles et déguster frais.'],note:'Myrtilles surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Blanc poulet cocotte poivron aubergine tomates riz basmati',kcal:421,p:28,g:61,l:7,portions:'4 pers.',ings:['Blanc poulet 90g','Riz basmati 65g','Poivron rouge 60g','Aubergine 75g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Dorer le poulet 5 min de chaque côté dans l\'huile.','Ajouter poivron et aubergine en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 10 min à couvert et servir sur le riz.'],note:'Cocotte du dimanche (30 min). Légumes de saison.'},
    {moment:'Collation',nom:'Porridge avoine framboises beurre de cacahuète famille',kcal:285,p:10,g:38,l:11,portions:'4 pers.',ings:['Flocons avoine 45g','Lait végétal 80g','Framboises 30g','Beurre cacahuète 12g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer les framboises et servir tiède.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Dîner',nom:'Soupe-repas lentilles vertes carotte champignons tomates concassées riz complet',kcal:504,p:23,g:86,l:7,portions:'4 pers.',ings:['Riz complet 50g','Lentilles vertes 70g','Carotte 60g','Champignons 60g','Tomates concassées 90g','Huile olive 5g'],steps:['Faire revenir la carotte et les champignons émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les lentilles vertes avec de l\'eau.','Porter à ébullition, cuire 20 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr banane myrtilles noix famille',kcal:412,p:18,g:58,l:13,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 70g','Banane 50g','Myrtilles 25g','Flocons avoine 45g','Noix 12g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la banane en rondelles.','Parsemer les flocons et les noix.','Disposer les myrtilles et déguster frais.'],note:'Myrtilles surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Blanc poulet cocotte poivron aubergine tomates riz basmati',kcal:421,p:28,g:61,l:7,portions:'4 pers.',ings:['Blanc poulet 90g','Riz basmati 65g','Poivron rouge 60g','Aubergine 75g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Dorer le poulet 5 min de chaque côté dans l\'huile.','Ajouter poivron et aubergine en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 10 min à couvert et servir sur le riz.'],note:'Cocotte du dimanche (30 min). Légumes de saison.'},
    {moment:'Collation',nom:'Porridge avoine framboises beurre de cacahuète famille',kcal:285,p:10,g:38,l:11,portions:'4 pers.',ings:['Flocons avoine 45g','Lait végétal 80g','Framboises 30g','Beurre cacahuète 12g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer les framboises et servir tiède.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Dîner',nom:'Soupe-repas lentilles vertes carotte champignons tomates concassées riz complet',kcal:504,p:23,g:86,l:7,portions:'4 pers.',ings:['Riz complet 50g','Lentilles vertes 70g','Carotte 60g','Champignons 60g','Tomates concassées 90g','Huile olive 5g'],steps:['Faire revenir la carotte et les champignons émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les lentilles vertes avec de l\'eau.','Porter à ébullition, cuire 20 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
];

const semaine2=[
  // LUNDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine pomme noix cannelle',kcal:328,p:9,g:46,l:12,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 100g','Pomme 70g','Noix 10g','Cannelle 1g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la pomme coupée en dés et la cannelle.','Parsemer les noix et servir tiède.'],note:'Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Wraps poulet avocat poivron épinards',kcal:419,p:31,g:39,l:16,portions:'2 adultes',ings:['Blanc poulet 100g','Tortillas complètes 60g','Poivron rouge 50g','Avocat 50g','Épinards frais 30g','Huile olive 3g'],steps:['Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter le poivron émincé, cuire 3 min.','Réchauffer les tortillas 1 min à la poêle.','Garnir de poulet, poivron, épinards et avocat en lamelles, rouler.'],note:'Repas rapide (12 min) et sans cuisson de féculent.'},
    {moment:'Collation',nom:'Fromage blanc mangue noisettes',kcal:200,p:15,g:18,l:7,portions:'2 adultes',ings:['Fromage blanc maigre 170g','Mangue 80g','Noisettes 12g'],steps:['Verser le fromage blanc dans un bol.','Couper la mangue en dés et disposer.','Parsemer les noisettes concassées.'],note:'Mangue disponible toute l\'année.'},
    {moment:'Dîner',nom:'Couscous pois chiches carotte courgette semoule complète',kcal:498,p:19,g:81,l:10,portions:'4 pers.',ings:['Semoule complète 55g','Pois chiches 60g','Carotte 60g','Courgette 60g','Oignon 20g','Huile olive 5g','Cumin 1g'],steps:['Faire revenir l\'oignon, la carotte et la courgette en dés dans l\'huile avec le cumin 8 min.','Ajouter les pois chiches et 10 cl d\'eau, mijoter 5 min.','Verser la semoule complète dans 6 cl d\'eau bouillante, couvrir 5 min et égrainer.','Servir les légumes et les pois chiches sur la semoule.'],note:'Couscous végétarien 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine pomme noix cannelle',kcal:370,p:10,g:53,l:14,portions:'2 adultes',ings:['Flocons avoine 56g','Lait végétal 113g','Pomme 79g','Noix 11g','Cannelle 1g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la pomme coupée en dés et la cannelle.','Parsemer les noix et servir tiède.'],note:'Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Wraps poulet avocat poivron épinards',kcal:473,p:35,g:44,l:18,portions:'2 adultes',ings:['Blanc poulet 113g','Tortillas complètes 68g','Poivron rouge 56g','Avocat 56g','Épinards frais 34g','Huile olive 3g'],steps:['Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter le poivron émincé, cuire 3 min.','Réchauffer les tortillas 1 min à la poêle.','Garnir de poulet, poivron, épinards et avocat en lamelles, rouler.'],note:'Repas rapide (12 min) et sans cuisson de féculent.'},
    {moment:'Collation',nom:'Fromage blanc mangue noisettes',kcal:226,p:16,g:20,l:8,portions:'2 adultes',ings:['Fromage blanc maigre 192g','Mangue 90g','Noisettes 14g'],steps:['Verser le fromage blanc dans un bol.','Couper la mangue en dés et disposer.','Parsemer les noisettes concassées.'],note:'Mangue disponible toute l\'année.'},
    {moment:'Dîner',nom:'Couscous pois chiches carotte courgette semoule complète',kcal:498,p:19,g:81,l:10,portions:'4 pers.',ings:['Semoule complète 55g','Pois chiches 60g','Carotte 60g','Courgette 60g','Oignon 20g','Huile olive 5g','Cumin 1g'],steps:['Faire revenir l\'oignon, la carotte et la courgette en dés dans l\'huile avec le cumin 8 min.','Ajouter les pois chiches et 10 cl d\'eau, mijoter 5 min.','Verser la semoule complète dans 6 cl d\'eau bouillante, couvrir 5 min et égrainer.','Servir les légumes et les pois chiches sur la semoule.'],note:'Couscous végétarien 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // MARDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Pudding chia kiwi mangue yaourt nature',kcal:299,p:10,g:39,l:13,portions:'2 adultes',ings:['Graines de chia 20g','Lait végétal 150g','Yaourt nature 100g','Kiwi 60g','Mangue 60g'],steps:['La veille : mélanger les graines de chia et le lait végétal, réserver au frais.','Le matin, ajouter le yaourt nature et mélanger.','Disposer le kiwi et la mangue en dés.'],note:'Préparer la veille.'},
    {moment:'Déjeuner',nom:'Cabillaud quinoa brocoli tomates cerises citron',kcal:455,p:38,g:53,l:11,portions:'2 adultes',ings:['Cabillaud 140g','Quinoa 70g','Brocoli 80g','Tomates cerises 60g','Huile olive 5g','Citron herbes fraîches 1g'],steps:['Rincer le quinoa et le cuire 12 min à l\'eau bouillante.','Cuire le brocoli vapeur 7 min.','Poêler le cabillaud 6 min à couvert dans l\'huile.','Ajouter les tomates cerises, cuire 2 min et servir avec le quinoa et le brocoli, filet de citron.'],note:'Poisson maigre, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt fruits mixé flocons noisettes',kcal:247,p:9,g:33,l:9,portions:'2 adultes',ings:['Yaourt fruits mixé 125g','Flocons avoine 20g','Noisettes 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noisettes concassées.'],note:'Encas simple et rapide.'},
    {moment:'Dîner',nom:'Pâtes complètes lentilles corail épinards tomates concassées',kcal:442,p:22,g:73,l:7,portions:'4 pers.',ings:['Pâtes complètes 50g','Lentilles corail 55g','Épinards frais 60g','Tomates concassées 80g','Oignon 20g','Huile olive 5g','Ail 1g'],steps:['Cuire les pâtes complètes 11 min.','Faire revenir l\'oignon et l\'ail dans l\'huile 3 min, ajouter les lentilles corail, les tomates concassées et 15 cl d\'eau.','Mijoter 12 min, ajouter les épinards 2 min.','Servir sur les pâtes.'],note:'Plat végétarien 17 min, sauce lentilles-tomate.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pudding chia kiwi mangue yaourt nature',kcal:338,p:11,g:44,l:14,portions:'2 adultes',ings:['Graines de chia 23g','Lait végétal 169g','Yaourt nature 113g','Kiwi 68g','Mangue 68g'],steps:['La veille : mélanger les graines de chia et le lait végétal, réserver au frais.','Le matin, ajouter le yaourt nature et mélanger.','Disposer le kiwi et la mangue en dés.'],note:'Préparer la veille.'},
    {moment:'Déjeuner',nom:'Cabillaud quinoa brocoli tomates cerises citron',kcal:514,p:43,g:60,l:12,portions:'2 adultes',ings:['Cabillaud 158g','Quinoa 79g','Brocoli 90g','Tomates cerises 68g','Huile olive 6g','Citron herbes fraîches 1g'],steps:['Rincer le quinoa et le cuire 12 min à l\'eau bouillante.','Cuire le brocoli vapeur 7 min.','Poêler le cabillaud 6 min à couvert dans l\'huile.','Ajouter les tomates cerises, cuire 2 min et servir avec le quinoa et le brocoli, filet de citron.'],note:'Poisson maigre, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt fruits mixé flocons noisettes',kcal:279,p:10,g:37,l:10,portions:'2 adultes',ings:['Yaourt fruits mixé 141g','Flocons avoine 23g','Noisettes 9g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noisettes concassées.'],note:'Encas simple et rapide.'},
    {moment:'Dîner',nom:'Pâtes complètes lentilles corail épinards tomates concassées',kcal:442,p:22,g:73,l:7,portions:'4 pers.',ings:['Pâtes complètes 50g','Lentilles corail 55g','Épinards frais 60g','Tomates concassées 80g','Oignon 20g','Huile olive 5g','Ail 1g'],steps:['Cuire les pâtes complètes 11 min.','Faire revenir l\'oignon et l\'ail dans l\'huile 3 min, ajouter les lentilles corail, les tomates concassées et 15 cl d\'eau.','Mijoter 12 min, ajouter les épinards 2 min.','Servir sur les pâtes.'],note:'Plat végétarien 17 min, sauce lentilles-tomate.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // MERCREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr kiwi noisettes flocons',kcal:300,p:20,g:37,l:9,portions:'2 adultes',ings:['Skyr 150g','Kiwi 80g','Noisettes 10g','Flocons avoine 30g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les noisettes.','Couper le kiwi en dés et disposer dessus.'],note:'Kiwi disponible toute l\'année.'},
    {moment:'Déjeuner',nom:'Boeuf maigre pâtes complètes champignons poivron oignon',kcal:456,p:31,g:55,l:12,portions:'2 adultes',ings:['Boeuf maigre 90g','Pâtes complètes 70g','Champignons 60g','Poivron rouge 50g','Oignon 30g','Huile olive 4g'],steps:['Cuire les pâtes complètes 11 min.','Poêler le boeuf maigre en lanières 5 min dans l\'huile.','Ajouter l\'oignon, le poivron et les champignons émincés, cuire 6 min.','Mélanger avec les pâtes et servir.'],note:'Champignons et poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse banane amandes',kcal:243,p:11,g:19,l:13,portions:'2 adultes',ings:['Petit suisse 120g','Banane 60g','Amandes 10g'],steps:['Verser le petit suisse dans un bol.','Couper la banane en rondelles.','Parsemer les amandes.'],note:'Encas simple et rapide.'},
    {moment:'Dîner',nom:'Frittata pommes de terre épinards gruyère',kcal:593,p:38,g:41,l:32,portions:'4 pers.',ings:['Oeufs 2 pièces','Pomme de terre 200g','Épinards frais 60g','Oignon 30g','Gruyère 20g','Huile olive 5g'],steps:['Couper les pommes de terre en petits dés et les cuire 10 min à la poêle dans l\'huile.','Ajouter l\'oignon émincé et les épinards, cuire 3 min.','Battre les oeufs, incorporer le gruyère râpé et verser sur les légumes.','Cuire à feu doux 5 min à couvert et servir.'],note:'Frittata complète 18 min, féculent = pomme de terre.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr kiwi noisettes flocons',kcal:339,p:22,g:42,l:10,portions:'2 adultes',ings:['Skyr 169g','Kiwi 90g','Noisettes 11g','Flocons avoine 34g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les noisettes.','Couper le kiwi en dés et disposer dessus.'],note:'Kiwi disponible toute l\'année.'},
    {moment:'Déjeuner',nom:'Boeuf maigre pâtes complètes champignons poivron oignon',kcal:515,p:35,g:62,l:14,portions:'2 adultes',ings:['Boeuf maigre 102g','Pâtes complètes 79g','Champignons 68g','Poivron rouge 56g','Oignon 34g','Huile olive 5g'],steps:['Cuire les pâtes complètes 11 min.','Poêler le boeuf maigre en lanières 5 min dans l\'huile.','Ajouter l\'oignon, le poivron et les champignons émincés, cuire 6 min.','Mélanger avec les pâtes et servir.'],note:'Champignons et poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse banane amandes',kcal:275,p:13,g:22,l:15,portions:'2 adultes',ings:['Petit suisse 136g','Banane 68g','Amandes 11g'],steps:['Verser le petit suisse dans un bol.','Couper la banane en rondelles.','Parsemer les amandes.'],note:'Encas simple et rapide.'},
    {moment:'Dîner',nom:'Frittata pommes de terre épinards gruyère',kcal:593,p:38,g:41,l:32,portions:'4 pers.',ings:['Oeufs 2 pièces','Pomme de terre 200g','Épinards frais 60g','Oignon 30g','Gruyère 20g','Huile olive 5g'],steps:['Couper les pommes de terre en petits dés et les cuire 10 min à la poêle dans l\'huile.','Ajouter l\'oignon émincé et les épinards, cuire 3 min.','Battre les oeufs, incorporer le gruyère râpé et verser sur les légumes.','Cuire à feu doux 5 min à couvert et servir.'],note:'Frittata complète 18 min, féculent = pomme de terre.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // JEUDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature mangue flocons noix',kcal:308,p:12,g:40,l:12,portions:'2 adultes',ings:['Yaourt nature 150g','Mangue 70g','Flocons avoine 35g','Noix 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Disposer la mangue en dés.'],note:'Petit-déjeuner simple et rapide.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz complet courgette aubergine',kcal:452,p:29,g:57,l:12,portions:'2 adultes',ings:['Cuisses poulet désossées 110g','Riz complet 70g','Courgette 60g','Aubergine 60g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter la courgette et l\'aubergine en dés, cuire 7 min.','Servir sur le riz.'],note:'Courgette et aubergine de fin de saison.'},
    {moment:'Collation',nom:'Yaourt nature poire noix',kcal:207,p:8,g:19,l:12,portions:'2 adultes',ings:['Yaourt nature 150g','Poire 70g','Noix 12g'],steps:['Verser le yaourt dans un bol.','Parsemer les noix.','Disposer la poire en dés.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Chili sin carne haricots rouges poivron quinoa',kcal:486,p:23,g:79,l:8,portions:'4 pers.',ings:['Quinoa 55g','Haricots rouges 60g','Poivron rouge 60g','Oignon 30g','Tomates concassées 90g','Huile olive 4g','Paprika 1g'],steps:['Rincer le quinoa et le cuire 12 min.','Faire revenir l\'oignon et le poivron en dés dans l\'huile avec le paprika 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 10 min.','Servir sur le quinoa.'],note:'Plat végétarien 18 min, épicé doux.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature mangue flocons noix',kcal:348,p:14,g:45,l:14,portions:'2 adultes',ings:['Yaourt nature 169g','Mangue 79g','Flocons avoine 40g','Noix 9g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Disposer la mangue en dés.'],note:'Petit-déjeuner simple et rapide.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz complet courgette aubergine',kcal:511,p:33,g:65,l:13,portions:'2 adultes',ings:['Cuisses poulet désossées 124g','Riz complet 79g','Courgette 68g','Aubergine 68g','Huile olive 6g'],steps:['Cuire le riz complet 20 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter la courgette et l\'aubergine en dés, cuire 7 min.','Servir sur le riz.'],note:'Courgette et aubergine de fin de saison.'},
    {moment:'Collation',nom:'Yaourt nature poire noix',kcal:234,p:9,g:21,l:14,portions:'2 adultes',ings:['Yaourt nature 169g','Poire 79g','Noix 14g'],steps:['Verser le yaourt dans un bol.','Parsemer les noix.','Disposer la poire en dés.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Chili sin carne haricots rouges poivron quinoa',kcal:486,p:23,g:79,l:8,portions:'4 pers.',ings:['Quinoa 55g','Haricots rouges 60g','Poivron rouge 60g','Oignon 30g','Tomates concassées 90g','Huile olive 4g','Paprika 1g'],steps:['Rincer le quinoa et le cuire 12 min.','Faire revenir l\'oignon et le poivron en dés dans l\'huile avec le paprika 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 10 min.','Servir sur le quinoa.'],note:'Plat végétarien 18 min, épicé doux.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // VENDREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine pomme yaourt nature lait végétal',kcal:315,p:11,g:51,l:8,portions:'2 adultes',ings:['Flocons avoine 55g','Yaourt nature 90g','Lait végétal 60g','Pomme 70g'],steps:['Mélanger flocons + yaourt nature + lait végétal la veille au soir.','Le matin, couper la pomme et incorporer.','Déguster froid.'],note:'Préparer la veille. Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Sardines patate douce brocoli citron',kcal:430,p:31,g:45,l:15,portions:'2 adultes',ings:['Sardines à l\'huile 100g','Patate douce 200g','Brocoli 70g','Huile olive 3g','Citron herbes fraîches 1g'],steps:['Couper la patate douce en dés et la cuire vapeur 12 min avec le brocoli.','Égoutter les sardines.','Assembler patate douce + brocoli + sardines, filet d\'huile et de citron.'],note:'Poisson gras riche en oméga-3, patate douce d\'automne.'},
    {moment:'Collation',nom:'Fromage blanc kiwi noix',kcal:204,p:15,g:18,l:9,portions:'2 adultes',ings:['Fromage blanc maigre 170g','Kiwi 80g','Noix 12g'],steps:['Verser le fromage blanc dans un bol.','Couper le kiwi en dés et disposer.','Parsemer les noix.'],note:'Kiwi disponible toute l\'année.'},
    {moment:'Dîner',nom:'Salade tiède lentilles vertes pommes de terre champignons oeuf',kcal:538,p:33,g:65,l:16,portions:'4 pers.',ings:['Lentilles vertes 65g','Pomme de terre 150g','Champignons 60g','Oignon 20g','Oeufs 1 pièce','Huile olive 5g','Moutarde 5g'],steps:['Cuire les lentilles vertes 20 min à l\'eau bouillante avec les pommes de terre en dés.','Cuire l\'oeuf 9 min à part.','Poêler les champignons et l\'oignon 5 min dans l\'huile.','Mélanger le tout tiède avec la moutarde et l\'oeuf en quartiers.'],note:'Salade tiède complète 20 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine pomme yaourt nature lait végétal',kcal:355,p:13,g:58,l:9,portions:'2 adultes',ings:['Flocons avoine 62g','Yaourt nature 102g','Lait végétal 68g','Pomme 79g'],steps:['Mélanger flocons + yaourt nature + lait végétal la veille au soir.','Le matin, couper la pomme et incorporer.','Déguster froid.'],note:'Préparer la veille. Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Sardines patate douce brocoli citron',kcal:486,p:35,g:51,l:17,portions:'2 adultes',ings:['Sardines à l\'huile 113g','Patate douce 226g','Brocoli 79g','Huile olive 3g','Citron herbes fraîches 1g'],steps:['Couper la patate douce en dés et la cuire vapeur 12 min avec le brocoli.','Égoutter les sardines.','Assembler patate douce + brocoli + sardines, filet d\'huile et de citron.'],note:'Poisson gras riche en oméga-3, patate douce d\'automne.'},
    {moment:'Collation',nom:'Fromage blanc kiwi noix',kcal:230,p:16,g:20,l:10,portions:'2 adultes',ings:['Fromage blanc maigre 192g','Kiwi 90g','Noix 14g'],steps:['Verser le fromage blanc dans un bol.','Couper le kiwi en dés et disposer.','Parsemer les noix.'],note:'Kiwi disponible toute l\'année.'},
    {moment:'Dîner',nom:'Salade tiède lentilles vertes pommes de terre champignons oeuf',kcal:538,p:33,g:65,l:16,portions:'4 pers.',ings:['Lentilles vertes 65g','Pomme de terre 150g','Champignons 60g','Oignon 20g','Oeufs 1 pièce','Huile olive 5g','Moutarde 5g'],steps:['Cuire les lentilles vertes 20 min à l\'eau bouillante avec les pommes de terre en dés.','Cuire l\'oeuf 9 min à part.','Poêler les champignons et l\'oignon 5 min dans l\'huile.','Mélanger le tout tiède avec la moutarde et l\'oeuf en quartiers.'],note:'Salade tiède complète 20 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // SAMEDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine poire yaourt miel famille',kcal:397,p:22,g:44,l:16,portions:'4 pers.',ings:['Flocons avoine mixés 40g','Oeufs 1 pièce','Lait végétal 30g','Yaourt nature 80g','Poire 60g','Miel 5g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf et le lait végétal en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, poire en dés et miel.'],note:'Les enfants adorent ! Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Boulettes boeuf haché maigre carotte courgette riz basmati sauce tomate',kcal:490,p:24,g:66,l:14,portions:'4 pers.',ings:['Boeuf haché maigre 80g','Riz basmati 70g','Carotte 60g','Courgette 60g','Tomates concassées 80g','Oignon 20g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Façonner le boeuf haché en boulettes avec l\'oignon haché.','Dorer les boulettes 6 min dans l\'huile, ajouter la carotte et la courgette en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 10 min et servir sur le riz.'],note:'Plat du week-end (30 min).'},
    {moment:'Collation',nom:'Fromage blanc mangue kiwi noisettes famille',kcal:175,p:11,g:21,l:5,portions:'4 pers.',ings:['Fromage blanc maigre 130g','Mangue 60g','Kiwi 50g','Noisettes 8g'],steps:['Couper la mangue et le kiwi en dés.','Verser sur le fromage blanc.','Parsemer les noisettes.'],note:'Fruits disponibles toute l\'année.'},
    {moment:'Dîner',nom:'Cuisses poulet rôties pommes de terre carotte oignon',kcal:432,p:31,g:51,l:12,portions:'4 pers.',ings:['Cuisses poulet désossées 120g','Pomme de terre 250g','Carotte 60g','Oignon 30g','Huile olive 6g','Herbes de Provence 2g'],steps:['Préchauffer le four à 200°C.','Couper pommes de terre, carotte et oignon en gros dés.','Disposer dans un plat avec l\'huile et les herbes, déposer les cuisses de poulet dessus.','Rôtir 35 min en retournant à mi-cuisson.'],note:'Plat du week-end au four (40 min), féculent = pomme de terre.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine poire yaourt miel famille',kcal:397,p:22,g:44,l:16,portions:'4 pers.',ings:['Flocons avoine mixés 40g','Oeufs 1 pièce','Lait végétal 30g','Yaourt nature 80g','Poire 60g','Miel 5g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf et le lait végétal en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, poire en dés et miel.'],note:'Les enfants adorent ! Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Boulettes boeuf haché maigre carotte courgette riz basmati sauce tomate',kcal:490,p:24,g:66,l:14,portions:'4 pers.',ings:['Boeuf haché maigre 80g','Riz basmati 70g','Carotte 60g','Courgette 60g','Tomates concassées 80g','Oignon 20g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Façonner le boeuf haché en boulettes avec l\'oignon haché.','Dorer les boulettes 6 min dans l\'huile, ajouter la carotte et la courgette en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 10 min et servir sur le riz.'],note:'Plat du week-end (30 min).'},
    {moment:'Collation',nom:'Fromage blanc mangue kiwi noisettes famille',kcal:175,p:11,g:21,l:5,portions:'4 pers.',ings:['Fromage blanc maigre 130g','Mangue 60g','Kiwi 50g','Noisettes 8g'],steps:['Couper la mangue et le kiwi en dés.','Verser sur le fromage blanc.','Parsemer les noisettes.'],note:'Fruits disponibles toute l\'année.'},
    {moment:'Dîner',nom:'Cuisses poulet rôties pommes de terre carotte oignon',kcal:432,p:31,g:51,l:12,portions:'4 pers.',ings:['Cuisses poulet désossées 120g','Pomme de terre 250g','Carotte 60g','Oignon 30g','Huile olive 6g','Herbes de Provence 2g'],steps:['Préchauffer le four à 200°C.','Couper pommes de terre, carotte et oignon en gros dés.','Disposer dans un plat avec l\'huile et les herbes, déposer les cuisses de poulet dessus.','Rôtir 35 min en retournant à mi-cuisson.'],note:'Plat du week-end au four (40 min), féculent = pomme de terre.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // DIMANCHE
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr yaourt fruits mixé poire noisettes famille',kcal:330,p:16,g:45,l:10,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 65g','Poire 60g','Noisettes 10g','Flocons avoine 35g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la poire en dés.','Parsemer les flocons et les noisettes.','Déguster frais.'],note:'Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Poulet curry coco patate douce épinards riz basmati',kcal:509,p:30,g:67,l:15,portions:'4 pers.',ings:['Cuisses poulet désossées 100g','Lait de coco 40g','Patate douce 100g','Épinards frais 60g','Riz basmati 55g','Curry 2g'],steps:['Cuire le riz basmati 12 min.','Couper le poulet en dés et la patate douce en petits dés.','Faire dorer le poulet 5 min sans matière grasse ajoutée, ajouter la patate douce, le curry et le lait de coco, mijoter 15 min.','Ajouter les épinards 2 min et servir sur le riz.'],note:'Plat du week-end (30 min), curry doux pour les enfants.'},
    {moment:'Collation',nom:'Smoothie bowl banane mangue yaourt chia famille',kcal:225,p:8,g:35,l:7,portions:'4 pers.',ings:['Banane 60g','Mangue 60g','Yaourt nature 100g','Graines de chia 10g','Lait végétal 60g'],steps:['Mixer la banane, la mangue, le yaourt nature et le lait végétal.','Verser dans un bol et parsemer de graines de chia.'],note:'Goûter frais du week-end.'},
    {moment:'Dîner',nom:'Pâtes complètes butternut pois chiches épinards parmesan',kcal:504,p:24,g:73,l:13,portions:'4 pers.',ings:['Pâtes complètes 55g','Pois chiches 45g','Courge butternut 80g','Épinards frais 50g','Parmesan 15g','Huile olive 4g'],steps:['Cuire les pâtes complètes 11 min.','Cuire la courge butternut en petits dés 10 min dans l\'huile avec 5 cl d\'eau.','Ajouter les pois chiches et les épinards, cuire 3 min.','Mélanger avec les pâtes et parsemer de parmesan.'],note:'Plat du dimanche soir (25 min), légumes d\'automne.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr yaourt fruits mixé poire noisettes famille',kcal:330,p:16,g:45,l:10,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 65g','Poire 60g','Noisettes 10g','Flocons avoine 35g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la poire en dés.','Parsemer les flocons et les noisettes.','Déguster frais.'],note:'Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Poulet curry coco patate douce épinards riz basmati',kcal:509,p:30,g:67,l:15,portions:'4 pers.',ings:['Cuisses poulet désossées 100g','Lait de coco 40g','Patate douce 100g','Épinards frais 60g','Riz basmati 55g','Curry 2g'],steps:['Cuire le riz basmati 12 min.','Couper le poulet en dés et la patate douce en petits dés.','Faire dorer le poulet 5 min sans matière grasse ajoutée, ajouter la patate douce, le curry et le lait de coco, mijoter 15 min.','Ajouter les épinards 2 min et servir sur le riz.'],note:'Plat du week-end (30 min), curry doux pour les enfants.'},
    {moment:'Collation',nom:'Smoothie bowl banane mangue yaourt chia famille',kcal:225,p:8,g:35,l:7,portions:'4 pers.',ings:['Banane 60g','Mangue 60g','Yaourt nature 100g','Graines de chia 10g','Lait végétal 60g'],steps:['Mixer la banane, la mangue, le yaourt nature et le lait végétal.','Verser dans un bol et parsemer de graines de chia.'],note:'Goûter frais du week-end.'},
    {moment:'Dîner',nom:'Pâtes complètes butternut pois chiches épinards parmesan',kcal:504,p:24,g:73,l:13,portions:'4 pers.',ings:['Pâtes complètes 55g','Pois chiches 45g','Courge butternut 80g','Épinards frais 50g','Parmesan 15g','Huile olive 4g'],steps:['Cuire les pâtes complètes 11 min.','Cuire la courge butternut en petits dés 10 min dans l\'huile avec 5 cl d\'eau.','Ajouter les pois chiches et les épinards, cuire 3 min.','Mélanger avec les pâtes et parsemer de parmesan.'],note:'Plat du dimanche soir (25 min), légumes d\'automne.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
];



const semaines=[semaine1, semaine2];
const semaineLabels=['Semaine en cours','Semaine suivante'];
