// ╔══════════════════════════════════════════════════════════════╗
// ║  DONNÉES MENUS — mis à jour chaque mardi par cowork          ║
// ║  Ne modifier que semaine1 et semaine2                        ║
// ╚══════════════════════════════════════════════════════════════╝

// ── DONNÉES SEMAINE 1 ──────────────────────────────────────────
const semaine1=[
  // LUNDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr banane myrtilles flocons amandes',kcal:296,p:19,g:41,l:7,portions:'2 adultes',ings:['Skyr 150g','Banane 70g','Myrtilles 40g','Flocons avoine 20g','Amandes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les amandes.','Couper la banane en rondelles.','Disposer les myrtilles et déguster.'],note:'Myrtilles d\'automne (surgelées acceptées).'},
    {moment:'Déjeuner',nom:'Blanc poulet riz basmati épinards champignons',kcal:444,p:33,g:62,l:7,portions:'2 adultes',ings:['Blanc poulet 100g','Riz basmati 75g','Épinards frais 70g','Champignons 50g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter les champignons émincés, cuire 4 min.','Ajouter les épinards, cuire 2 min et servir avec le riz.'],note:'Épinards et champignons d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt nature banane flocons amandes',kcal:265,p:11,g:31,l:12,portions:'2 adultes',ings:['Yaourt nature 150g','Banane 60g','Flocons avoine 15g','Amandes 12g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les amandes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et rapide.'},
    {moment:'Dîner',nom:'Lentilles vertes courgette poivron tomates concassées riz complet',kcal:506,p:22,g:86,l:7,portions:'4 pers.',ings:['Riz complet 55g','Lentilles vertes 70g','Courgette 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Faire revenir la courgette et le poivron dans l\'huile 5 min.','Ajouter les lentilles vertes et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr banane myrtilles flocons amandes',kcal:383,p:25,g:53,l:9,portions:'2 adultes',ings:['Skyr 194g','Banane 90g','Myrtilles 52g','Flocons avoine 26g','Amandes 13g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les amandes.','Couper la banane en rondelles.','Disposer les myrtilles et déguster.'],note:'Myrtilles d\'automne (surgelées acceptées).'},
    {moment:'Déjeuner',nom:'Blanc poulet riz basmati épinards champignons',kcal:553,p:41,g:78,l:8,portions:'2 adultes',ings:['Blanc poulet 125g','Riz basmati 94g','Épinards frais 88g','Champignons 62g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter les champignons émincés, cuire 4 min.','Ajouter les épinards, cuire 2 min et servir avec le riz.'],note:'Épinards et champignons d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt nature banane flocons amandes',kcal:324,p:14,g:38,l:14,portions:'2 adultes',ings:['Yaourt nature 183g','Banane 73g','Flocons avoine 18g','Amandes 15g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les amandes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et rapide.'},
    {moment:'Dîner',nom:'Lentilles vertes courgette poivron tomates concassées riz complet',kcal:506,p:22,g:86,l:7,portions:'4 pers.',ings:['Riz complet 55g','Lentilles vertes 70g','Courgette 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Faire revenir la courgette et le poivron dans l\'huile 5 min.','Ajouter les lentilles vertes et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // MARDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine banane beurre de cacahuète lait végétal',kcal:341,p:11,g:51,l:11,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 80g','Banane 60g','Beurre cacahuète 12g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la banane coupée en rondelles.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Petit-déjeuner énergétique.'},
    {moment:'Déjeuner',nom:'Maquereau fumé riz complet brocoli tomates citron',kcal:460,p:29,g:55,l:13,portions:'2 adultes',ings:['Maquereau fumé en boîte 90g','Riz complet 65g','Brocoli 70g','Tomates 60g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Émietter le maquereau fumé.','Assembler riz + maquereau + brocoli + tomates, filet de citron.'],note:'Poisson gras riche en oméga-3, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr banane noisettes',kcal:165,p:13,g:17,l:5,portions:'2 adultes',ings:['Skyr 130g','Banane 50g','Noisettes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les noisettes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et économique.'},
    {moment:'Dîner',nom:'Pois chiches courgette aubergine tomates concassées riz basmati',kcal:480,p:18,g:82,l:8,portions:'4 pers.',ings:['Riz basmati 50g','Pois chiches 65g','Courgette 60g','Aubergine 50g','Tomates concassées 60g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir la courgette et l\'aubergine dans l\'huile 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine banane beurre de cacahuète lait végétal',kcal:435,p:14,g:66,l:14,portions:'2 adultes',ings:['Flocons avoine 64g','Lait végétal 103g','Banane 77g','Beurre cacahuète 15g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la banane coupée en rondelles.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Petit-déjeuner énergétique.'},
    {moment:'Déjeuner',nom:'Maquereau fumé riz complet brocoli tomates citron',kcal:573,p:36,g:69,l:16,portions:'2 adultes',ings:['Maquereau fumé en boîte 112g','Riz complet 81g','Brocoli 88g','Tomates 75g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Émietter le maquereau fumé.','Assembler riz + maquereau + brocoli + tomates, filet de citron.'],note:'Poisson gras riche en oméga-3, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr banane noisettes',kcal:203,p:16,g:21,l:6,portions:'2 adultes',ings:['Skyr 159g','Banane 61g','Noisettes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les noisettes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et économique.'},
    {moment:'Dîner',nom:'Pois chiches courgette aubergine tomates concassées riz basmati',kcal:480,p:18,g:82,l:8,portions:'4 pers.',ings:['Riz basmati 50g','Pois chiches 65g','Courgette 60g','Aubergine 50g','Tomates concassées 60g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir la courgette et l\'aubergine dans l\'huile 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // MERCREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine kiwi skyr amandes lait végétal',kcal:412,p:20,g:63,l:9,portions:'2 adultes',ings:['Flocons avoine 75g','Skyr 90g','Lait végétal 50g','Kiwi 70g','Amandes 5g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper le kiwi et incorporer.','Parsemer les amandes.','Déguster froid.'],note:'Préparer la veille. Kiwi de saison.'},
    {moment:'Déjeuner',nom:'Boeuf maigre riz basmati poivron oignon',kcal:479,p:26,g:66,l:12,portions:'2 adultes',ings:['Boeuf maigre 90g','Riz basmati 75g','Poivron rouge 70g','Oignon 40g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Émincer l\'oignon, faire revenir avec le poivron dans l\'huile 5 min.','Poêler le boeuf maigre en lanières 5 min.','Mélanger avec le riz et servir.'],note:'Poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse kiwi miel amandes',kcal:241,p:11,g:19,l:14,portions:'2 adultes',ings:['Petit suisse 130g','Kiwi 60g','Miel 5g','Amandes 8g'],steps:['Couper le kiwi en dés.','Verser sur le petit suisse.','Parsemer les amandes et arroser de miel.'],note:'Kiwi de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade riz complet courgette poivron tomates oignon',kcal:348,p:17,g:36,l:15,portions:'4 pers.',ings:['Oeufs 2 pièces','Riz complet 35g','Courgette 50g','Poivron rouge 50g','Tomates 60g','Oignon 30g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Émincer l\'oignon, faire revenir avec le poivron et la courgette dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs, verser sur les légumes, cuire à feu doux 4 min et servir avec le riz.'],note:'Pipérade complète, 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine kiwi skyr amandes lait végétal',kcal:530,p:26,g:82,l:12,portions:'2 adultes',ings:['Flocons avoine 97g','Skyr 116g','Lait végétal 64g','Kiwi 90g','Amandes 6g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper le kiwi et incorporer.','Parsemer les amandes.','Déguster froid.'],note:'Préparer la veille. Kiwi de saison.'},
    {moment:'Déjeuner',nom:'Boeuf maigre riz basmati poivron oignon',kcal:597,p:32,g:82,l:15,portions:'2 adultes',ings:['Boeuf maigre 112g','Riz basmati 94g','Poivron rouge 88g','Oignon 50g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Émincer l\'oignon, faire revenir avec le poivron dans l\'huile 5 min.','Poêler le boeuf maigre en lanières 5 min.','Mélanger avec le riz et servir.'],note:'Poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse kiwi miel amandes',kcal:296,p:14,g:23,l:17,portions:'2 adultes',ings:['Petit suisse 159g','Kiwi 73g','Miel 6g','Amandes 10g'],steps:['Couper le kiwi en dés.','Verser sur le petit suisse.','Parsemer les amandes et arroser de miel.'],note:'Kiwi de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade riz complet courgette poivron tomates oignon',kcal:348,p:17,g:36,l:15,portions:'4 pers.',ings:['Oeufs 2 pièces','Riz complet 35g','Courgette 50g','Poivron rouge 50g','Tomates 60g','Oignon 30g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Émincer l\'oignon, faire revenir avec le poivron et la courgette dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs, verser sur les légumes, cuire à feu doux 4 min et servir avec le riz.'],note:'Pipérade complète, 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // JEUDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature banane flocons noix',kcal:355,p:14,g:50,l:13,portions:'2 adultes',ings:['Yaourt nature 150g','Banane 60g','Flocons avoine 45g','Noix 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Couper la banane en rondelles et déguster frais.'],note:'Petit-déjeuner simple et économique.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz complet épinards tomates',kcal:463,p:26,g:57,l:14,portions:'2 adultes',ings:['Cuisses poulet désossées 95g','Riz complet 70g','Épinards frais 80g','Tomates 60g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les épinards, cuire 3 min.','Ajouter les tomates, cuire 2 min et servir sur le riz.'],note:'Épinards d\'automne de saison.'},
    {moment:'Collation',nom:'Fromage blanc poire miel amandes',kcal:153,p:11,g:16,l:4,portions:'2 adultes',ings:['Fromage blanc maigre 140g','Poire 50g','Miel 5g','Amandes 8g'],steps:['Verser le fromage blanc dans un bol.','Couper la poire en dés.','Parsemer les amandes et arroser de miel.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Haricots rouges potiron poivron tomates concassées riz complet',kcal:515,p:21,g:89,l:8,portions:'4 pers.',ings:['Riz complet 55g','Haricots rouges 70g','Potiron 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Faire revenir le potiron et le poivron dans l\'huile 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature banane flocons noix',kcal:456,p:18,g:64,l:16,portions:'2 adultes',ings:['Yaourt nature 194g','Banane 77g','Flocons avoine 58g','Noix 10g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Couper la banane en rondelles et déguster frais.'],note:'Petit-déjeuner simple et économique.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz complet épinards tomates',kcal:578,p:33,g:72,l:17,portions:'2 adultes',ings:['Cuisses poulet désossées 119g','Riz complet 88g','Épinards frais 100g','Tomates 75g','Huile olive 6g'],steps:['Cuire le riz complet 20 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les épinards, cuire 3 min.','Ajouter les tomates, cuire 2 min et servir sur le riz.'],note:'Épinards d\'automne de saison.'},
    {moment:'Collation',nom:'Fromage blanc poire miel amandes',kcal:188,p:14,g:20,l:5,portions:'2 adultes',ings:['Fromage blanc maigre 171g','Poire 61g','Miel 6g','Amandes 10g'],steps:['Verser le fromage blanc dans un bol.','Couper la poire en dés.','Parsemer les amandes et arroser de miel.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Haricots rouges potiron poivron tomates concassées riz complet',kcal:515,p:21,g:89,l:8,portions:'4 pers.',ings:['Riz complet 55g','Haricots rouges 70g','Potiron 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Faire revenir le potiron et le poivron dans l\'huile 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // VENDREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine framboises beurre de cacahuète lait végétal',kcal:349,p:12,g:50,l:12,portions:'2 adultes',ings:['Flocons avoine 60g','Lait végétal 80g','Framboises 50g','Beurre cacahuète 12g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer les framboises.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Thon riz basmati brocoli carotte citron',kcal:432,p:34,g:59,l:7,portions:'2 adultes',ings:['Thon en boîte 100g','Riz basmati 65g','Brocoli 70g','Carotte 50g','Huile olive 5g','Citron herbes fraîches 1g'],steps:['Cuire le riz basmati 12 min.','Cuire le brocoli vapeur 7 min.','Égoutter le thon et râper la carotte.','Assembler riz + thon + brocoli + carotte, filet d\'huile et de citron.'],note:'Poisson maigre, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr banane amandes',kcal:182,p:14,g:20,l:5,portions:'2 adultes',ings:['Skyr 130g','Banane 60g','Amandes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et économique.'},
    {moment:'Dîner',nom:'Lentilles corail épinards champignons tomates concassées riz basmati',kcal:514,p:25,g:89,l:6,portions:'4 pers.',ings:['Riz basmati 55g','Lentilles corail 70g','Épinards frais 60g','Champignons 60g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons dans l\'huile 5 min.','Ajouter les épinards, les lentilles corail et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine framboises beurre de cacahuète lait végétal',kcal:446,p:15,g:64,l:16,portions:'2 adultes',ings:['Flocons avoine 77g','Lait végétal 103g','Framboises 64g','Beurre cacahuète 15g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer les framboises.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Thon riz basmati brocoli carotte citron',kcal:537,p:42,g:74,l:8,portions:'2 adultes',ings:['Thon en boîte 125g','Riz basmati 81g','Brocoli 88g','Carotte 62g','Huile olive 6g','Citron herbes fraîches 1g'],steps:['Cuire le riz basmati 12 min.','Cuire le brocoli vapeur 7 min.','Égoutter le thon et râper la carotte.','Assembler riz + thon + brocoli + carotte, filet d\'huile et de citron.'],note:'Poisson maigre, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr banane amandes',kcal:220,p:18,g:24,l:6,portions:'2 adultes',ings:['Skyr 159g','Banane 73g','Amandes 12g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Couper la banane en rondelles et déguster.'],note:'Encas simple et économique.'},
    {moment:'Dîner',nom:'Lentilles corail épinards champignons tomates concassées riz basmati',kcal:514,p:25,g:89,l:6,portions:'4 pers.',ings:['Riz basmati 55g','Lentilles corail 70g','Épinards frais 60g','Champignons 60g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons dans l\'huile 5 min.','Ajouter les épinards, les lentilles corail et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // SAMEDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine myrtilles miel yaourt amandes famille',kcal:407,p:18,g:50,l:15,portions:'4 pers.',ings:['Flocons avoine mixés 45g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 70g','Myrtilles 30g','Miel 5g','Amandes 10g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf et le lait végétal en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, myrtilles, amandes et miel.'],note:'Les enfants adorent ! Myrtilles surgelées acceptées.'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé poivron aubergine riz complet',kcal:459,p:18,g:64,l:14,portions:'4 pers.',ings:['Boeuf haché maigre 56g','Riz complet 75g','Poivron rouge 90g','Aubergine 60g','Huile olive 6g'],steps:['Cuire le riz complet 20 min.','Couper le poivron et l\'aubergine.','Griller les légumes à la poêle 8 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec riz et légumes.'],note:'Plat du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc framboises myrtilles miel amandes famille',kcal:164,p:12,g:16,l:6,portions:'4 pers.',ings:['Fromage blanc maigre 130g','Framboises 30g','Myrtilles 30g','Miel 5g','Amandes 10g'],steps:['Verser le fromage blanc dans un bol.','Disposer les framboises et les myrtilles.','Parsemer les amandes et arroser de miel.'],note:'Fruits rouges surgelés acceptés toute l\'année.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte champignons tomates riz basmati',kcal:510,p:27,g:68,l:14,portions:'4 pers.',ings:['Cuisses poulet désossées 95g','Riz basmati 75g','Carotte 60g','Champignons 60g','Tomates concassées 70g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et champignons, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine myrtilles miel yaourt amandes famille',kcal:407,p:18,g:50,l:15,portions:'4 pers.',ings:['Flocons avoine mixés 45g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 70g','Myrtilles 30g','Miel 5g','Amandes 10g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf et le lait végétal en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, myrtilles, amandes et miel.'],note:'Les enfants adorent ! Myrtilles surgelées acceptées.'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé poivron aubergine riz complet',kcal:459,p:18,g:64,l:14,portions:'4 pers.',ings:['Boeuf haché maigre 56g','Riz complet 75g','Poivron rouge 90g','Aubergine 60g','Huile olive 6g'],steps:['Cuire le riz complet 20 min.','Couper le poivron et l\'aubergine.','Griller les légumes à la poêle 8 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec riz et légumes.'],note:'Plat du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc framboises myrtilles miel amandes famille',kcal:164,p:12,g:16,l:6,portions:'4 pers.',ings:['Fromage blanc maigre 130g','Framboises 30g','Myrtilles 30g','Miel 5g','Amandes 10g'],steps:['Verser le fromage blanc dans un bol.','Disposer les framboises et les myrtilles.','Parsemer les amandes et arroser de miel.'],note:'Fruits rouges surgelés acceptés toute l\'année.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte champignons tomates riz basmati',kcal:510,p:27,g:68,l:14,portions:'4 pers.',ings:['Cuisses poulet désossées 95g','Riz basmati 75g','Carotte 60g','Champignons 60g','Tomates concassées 70g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et champignons, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // DIMANCHE
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr banane myrtilles noix famille',kcal:412,p:18,g:58,l:13,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 70g','Banane 50g','Myrtilles 25g','Flocons avoine 45g','Noix 12g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la banane en rondelles.','Parsemer les flocons et les noix.','Disposer les myrtilles et déguster frais.'],note:'Myrtilles surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Blanc poulet cocotte poivron aubergine tomates riz basmati',kcal:421,p:28,g:61,l:7,portions:'4 pers.',ings:['Blanc poulet 90g','Riz basmati 65g','Poivron rouge 60g','Aubergine 75g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Dorer le poulet 5 min de chaque côté dans l\'huile.','Ajouter poivron et aubergine en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 10 min à couvert et servir sur le riz.'],note:'Cocotte du dimanche (30 min). Légumes de saison.'},
    {moment:'Collation',nom:'Porridge avoine framboises beurre de cacahuète famille',kcal:285,p:10,g:38,l:11,portions:'4 pers.',ings:['Flocons avoine 45g','Lait végétal 80g','Framboises 30g','Beurre cacahuète 12g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer les framboises et servir tiède.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Dîner',nom:'Soupe-repas lentilles vertes carotte champignons tomates concassées riz complet',kcal:504,p:23,g:86,l:7,portions:'4 pers.',ings:['Riz complet 50g','Lentilles vertes 70g','Carotte 60g','Champignons 60g','Tomates concassées 90g','Huile olive 5g'],steps:['Faire revenir la carotte et les champignons émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les lentilles vertes avec de l\'eau.','Porter à ébullition, cuire 20 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr banane myrtilles noix famille',kcal:412,p:18,g:58,l:13,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 70g','Banane 50g','Myrtilles 25g','Flocons avoine 45g','Noix 12g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la banane en rondelles.','Parsemer les flocons et les noix.','Disposer les myrtilles et déguster frais.'],note:'Myrtilles surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Blanc poulet cocotte poivron aubergine tomates riz basmati',kcal:421,p:28,g:61,l:7,portions:'4 pers.',ings:['Blanc poulet 90g','Riz basmati 65g','Poivron rouge 60g','Aubergine 75g','Tomates concassées 70g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Dorer le poulet 5 min de chaque côté dans l\'huile.','Ajouter poivron et aubergine en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 10 min à couvert et servir sur le riz.'],note:'Cocotte du dimanche (30 min). Légumes de saison.'},
    {moment:'Collation',nom:'Porridge avoine framboises beurre de cacahuète famille',kcal:285,p:10,g:38,l:11,portions:'4 pers.',ings:['Flocons avoine 45g','Lait végétal 80g','Framboises 30g','Beurre cacahuète 12g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer les framboises et servir tiède.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Dîner',nom:'Soupe-repas lentilles vertes carotte champignons tomates concassées riz complet',kcal:504,p:23,g:86,l:7,portions:'4 pers.',ings:['Riz complet 50g','Lentilles vertes 70g','Carotte 60g','Champignons 60g','Tomates concassées 90g','Huile olive 5g'],steps:['Faire revenir la carotte et les champignons émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les lentilles vertes avec de l\'eau.','Porter à ébullition, cuire 20 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
];

const semaine2=[
  // LUNDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr kiwi myrtilles noisettes',kcal:298,p:20,g:40,l:8,portions:'2 adultes',ings:['Skyr 150g','Kiwi 55g','Myrtilles 45g','Flocons avoine 30g','Noisettes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les noisettes.','Couper le kiwi en dés.','Disposer sur le skyr avec les myrtilles et déguster.'],note:'Myrtilles surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Blanc poulet riz basmati brocoli poivron rouge',kcal:470,p:34,g:66,l:7,portions:'2 adultes',ings:['Blanc poulet 110g','Riz basmati 75g','Brocoli 80g','Poivron rouge 50g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Cuire le brocoli vapeur 7 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter le poivron émincé, cuire 4 min et servir avec riz et brocoli.'],note:'Brocoli et poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt nature poire noisettes',kcal:203,p:9,g:19,l:12,portions:'2 adultes',ings:['Yaourt nature 180g','Poire 60g','Noisettes 10g'],steps:['Verser le yaourt dans un bol.','Parsemer les noisettes.','Couper la poire en dés et déguster.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Lentilles corail patate douce poireaux tomates concassées riz complet',kcal:494,p:22,g:89,l:6,portions:'4 pers.',ings:['Riz complet 45g','Lentilles corail 65g','Patate douce 60g','Poireaux 50g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Cuire les lentilles corail 15 min à l\'eau bouillante.','Faire revenir la patate douce et les poireaux dans l\'huile 7 min.','Ajouter les tomates concassées et les lentilles cuites, mijoter 4 min et servir sur le riz.'],note:'Plat végétarien d\'automne 19 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr kiwi myrtilles noisettes',kcal:337,p:22,g:45,l:9,portions:'2 adultes',ings:['Skyr 169g','Kiwi 62g','Myrtilles 51g','Flocons avoine 34g','Noisettes 9g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les noisettes.','Couper le kiwi en dés.','Disposer sur le skyr avec les myrtilles et déguster.'],note:'Myrtilles surgelées acceptées toute l\'année.'},
    {moment:'Déjeuner',nom:'Blanc poulet riz basmati brocoli poivron rouge',kcal:532,p:39,g:75,l:8,portions:'2 adultes',ings:['Blanc poulet 124g','Riz basmati 85g','Brocoli 90g','Poivron rouge 56g','Huile olive 6g'],steps:['Cuire le riz basmati 12 min.','Cuire le brocoli vapeur 7 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter le poivron émincé, cuire 4 min et servir avec riz et brocoli.'],note:'Brocoli et poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt nature poire noisettes',kcal:230,p:10,g:21,l:13,portions:'2 adultes',ings:['Yaourt nature 203g','Poire 68g','Noisettes 11g'],steps:['Verser le yaourt dans un bol.','Parsemer les noisettes.','Couper la poire en dés et déguster.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Lentilles corail patate douce poireaux tomates concassées riz complet',kcal:494,p:22,g:89,l:6,portions:'4 pers.',ings:['Riz complet 45g','Lentilles corail 65g','Patate douce 60g','Poireaux 50g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Cuire les lentilles corail 15 min à l\'eau bouillante.','Faire revenir la patate douce et les poireaux dans l\'huile 7 min.','Ajouter les tomates concassées et les lentilles cuites, mijoter 4 min et servir sur le riz.'],note:'Plat végétarien d\'automne 19 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // MARDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine poire amandes lait végétal',kcal:315,p:10,g:48,l:9,portions:'2 adultes',ings:['Flocons avoine 55g','Lait végétal 80g','Poire 60g','Amandes 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la poire coupée en dés.','Disposer les amandes.','Servir tiède.'],note:'Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cabillaud riz basmati poivron tomates cerises citron',kcal:399,p:30,g:56,l:6,portions:'2 adultes',ings:['Cabillaud 130g','Riz basmati 65g','Poivron rouge 60g','Tomates cerises 60g','Huile olive 4g','Citron herbes fraîches 1g'],steps:['Cuire le riz basmati 12 min.','Émincer le poivron, faire revenir 5 min dans l\'huile.','Poêler le cabillaud 6 min à couvert.','Ajouter les tomates cerises, cuire 2 min et servir avec riz et poivron, filet de citron.'],note:'Poisson maigre, poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr framboises amandes',kcal:145,p:14,g:12,l:5,portions:'2 adultes',ings:['Skyr 130g','Framboises 55g','Amandes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Disposer les framboises et déguster.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Dîner',nom:'Haricots rouges champignons poireaux tomates concassées riz complet',kcal:452,p:21,g:78,l:6,portions:'4 pers.',ings:['Riz complet 45g','Haricots rouges 65g','Champignons 60g','Poireaux 50g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Faire revenir les champignons et les poireaux dans l\'huile 6 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 19 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine poire amandes lait végétal',kcal:356,p:11,g:54,l:11,portions:'2 adultes',ings:['Flocons avoine 62g','Lait végétal 90g','Poire 68g','Amandes 9g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la poire coupée en dés.','Disposer les amandes.','Servir tiède.'],note:'Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cabillaud riz basmati poivron tomates cerises citron',kcal:451,p:34,g:63,l:7,portions:'2 adultes',ings:['Cabillaud 147g','Riz basmati 73g','Poivron rouge 68g','Tomates cerises 68g','Huile olive 5g','Citron herbes fraîches 1g'],steps:['Cuire le riz basmati 12 min.','Émincer le poivron, faire revenir 5 min dans l\'huile.','Poêler le cabillaud 6 min à couvert.','Ajouter les tomates cerises, cuire 2 min et servir avec riz et poivron, filet de citron.'],note:'Poisson maigre, poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr framboises amandes',kcal:164,p:16,g:14,l:5,portions:'2 adultes',ings:['Skyr 147g','Framboises 62g','Amandes 9g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Disposer les framboises et déguster.'],note:'Framboises surgelées acceptées toute l\'année.'},
    {moment:'Dîner',nom:'Haricots rouges champignons poireaux tomates concassées riz complet',kcal:452,p:21,g:78,l:6,portions:'4 pers.',ings:['Riz complet 45g','Haricots rouges 65g','Champignons 60g','Poireaux 50g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Faire revenir les champignons et les poireaux dans l\'huile 6 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 19 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // MERCREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature banane flocons noix',kcal:302,p:12,g:40,l:12,portions:'2 adultes',ings:['Yaourt nature 150g','Banane 60g','Flocons avoine 30g','Noix 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Couper la banane en rondelles et déguster.'],note:'Petit-déjeuner simple et énergétique.'},
    {moment:'Déjeuner',nom:'Boeuf maigre pâtes complètes champignons poivron rouge',kcal:444,p:30,g:52,l:12,portions:'2 adultes',ings:['Boeuf maigre 90g','Pâtes complètes 70g','Champignons 60g','Poivron rouge 50g','Huile olive 4g'],steps:['Cuire les pâtes complètes 11 min.','Poêler le boeuf maigre en lanières 5 min dans l\'huile.','Ajouter les champignons et le poivron émincés, cuire 5 min.','Mélanger avec les pâtes et servir.'],note:'Champignons et poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse pomme amandes',kcal:196,p:9,g:13,l:12,portions:'2 adultes',ings:['Petit suisse 110g','Pomme 55g','Amandes 8g'],steps:['Verser le petit suisse dans un bol.','Parsemer les amandes.','Couper la pomme en dés et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade riz complet courgette poivron oignon tomates',kcal:491,p:30,g:38,l:25,portions:'4 pers.',ings:['Oeufs 2 pièces','Riz complet 35g','Courgette 50g','Poivron rouge 50g','Oignon 30g','Tomates 60g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Émincer l\'oignon, faire revenir avec le poivron et la courgette dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs, verser sur les légumes, cuire à feu doux 4 min et servir avec le riz.'],note:'Pipérade complète, 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature banane flocons noix',kcal:341,p:13,g:46,l:13,portions:'2 adultes',ings:['Yaourt nature 169g','Banane 68g','Flocons avoine 34g','Noix 9g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Couper la banane en rondelles et déguster.'],note:'Petit-déjeuner simple et énergétique.'},
    {moment:'Déjeuner',nom:'Boeuf maigre pâtes complètes champignons poivron rouge',kcal:502,p:34,g:59,l:14,portions:'2 adultes',ings:['Boeuf maigre 102g','Pâtes complètes 79g','Champignons 68g','Poivron rouge 56g','Huile olive 5g'],steps:['Cuire les pâtes complètes 11 min.','Poêler le boeuf maigre en lanières 5 min dans l\'huile.','Ajouter les champignons et le poivron émincés, cuire 5 min.','Mélanger avec les pâtes et servir.'],note:'Champignons et poivron d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse pomme amandes',kcal:221,p:11,g:14,l:13,portions:'2 adultes',ings:['Petit suisse 124g','Pomme 62g','Amandes 9g'],steps:['Verser le petit suisse dans un bol.','Parsemer les amandes.','Couper la pomme en dés et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade riz complet courgette poivron oignon tomates',kcal:491,p:30,g:38,l:25,portions:'4 pers.',ings:['Oeufs 2 pièces','Riz complet 35g','Courgette 50g','Poivron rouge 50g','Oignon 30g','Tomates 60g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Émincer l\'oignon, faire revenir avec le poivron et la courgette dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs, verser sur les légumes, cuire à feu doux 4 min et servir avec le riz.'],note:'Pipérade complète, 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // JEUDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine pomme skyr lait végétal',kcal:318,p:16,g:53,l:5,portions:'2 adultes',ings:['Flocons avoine 60g','Skyr 80g','Lait végétal 50g','Pomme 70g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper la pomme et incorporer.','Déguster froid.'],note:'Préparer la veille. Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz complet champignons patate douce',kcal:406,p:29,g:56,l:6,portions:'2 adultes',ings:['Cuisses poulet désossées 95g','Riz complet 60g','Champignons 60g','Patate douce 50g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les champignons et la patate douce en dés, cuire 6 min.','Servir sur le riz.'],note:'Champignons et patate douce d\'automne de saison.'},
    {moment:'Collation',nom:'Fromage blanc mangue miel amandes',kcal:161,p:12,g:18,l:4,portions:'2 adultes',ings:['Fromage blanc maigre 140g','Mangue 60g','Miel 5g','Amandes 8g'],steps:['Verser le fromage blanc dans un bol.','Couper la mangue en dés.','Parsemer les amandes et arroser de miel.'],note:'Mangue disponible toute l\'année.'},
    {moment:'Dîner',nom:'Pois chiches courgette poivron tomates concassées riz basmati',kcal:483,p:18,g:82,l:8,portions:'4 pers.',ings:['Riz basmati 50g','Pois chiches 65g','Courgette 60g','Poivron rouge 50g','Tomates concassées 60g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir la courgette et le poivron dans l\'huile 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine pomme skyr lait végétal',kcal:359,p:18,g:60,l:6,portions:'2 adultes',ings:['Flocons avoine 68g','Skyr 90g','Lait végétal 56g','Pomme 79g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper la pomme et incorporer.','Déguster froid.'],note:'Préparer la veille. Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz complet champignons patate douce',kcal:459,p:33,g:64,l:7,portions:'2 adultes',ings:['Cuisses poulet désossées 107g','Riz complet 68g','Champignons 68g','Patate douce 56g','Huile olive 5g'],steps:['Cuire le riz complet 20 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les champignons et la patate douce en dés, cuire 6 min.','Servir sur le riz.'],note:'Champignons et patate douce d\'automne de saison.'},
    {moment:'Collation',nom:'Fromage blanc mangue miel amandes',kcal:181,p:14,g:20,l:5,portions:'2 adultes',ings:['Fromage blanc maigre 158g','Mangue 68g','Miel 6g','Amandes 9g'],steps:['Verser le fromage blanc dans un bol.','Couper la mangue en dés.','Parsemer les amandes et arroser de miel.'],note:'Mangue disponible toute l\'année.'},
    {moment:'Dîner',nom:'Pois chiches courgette poivron tomates concassées riz basmati',kcal:483,p:18,g:82,l:8,portions:'4 pers.',ings:['Riz basmati 50g','Pois chiches 65g','Courgette 60g','Poivron rouge 50g','Tomates concassées 60g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir la courgette et le poivron dans l\'huile 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // VENDREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine poire beurre de cacahuète lait végétal',kcal:307,p:10,g:45,l:10,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 80g','Poire 55g','Beurre cacahuète 10g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la poire coupée en dés.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Sardines riz complet brocoli carotte citron',kcal:463,p:32,g:54,l:13,portions:'2 adultes',ings:['Sardines à l\'huile 100g','Riz complet 60g','Brocoli 65g','Carotte 55g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Égoutter les sardines et râper la carotte.','Assembler riz + sardines + brocoli + carotte, filet de citron.'],note:'Poisson gras riche en oméga-3, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr kiwi noix',kcal:156,p:13,g:14,l:6,portions:'2 adultes',ings:['Skyr 130g','Kiwi 55g','Noix 8g'],steps:['Verser le skyr dans un bol.','Parsemer les noix.','Disposer le kiwi en dés et déguster.'],note:'Kiwi disponible toute l\'année.'},
    {moment:'Dîner',nom:'Lentilles vertes champignons carotte tomates concassées riz basmati',kcal:469,p:22,g:82,l:5,portions:'4 pers.',ings:['Riz basmati 50g','Lentilles vertes 65g','Champignons 55g','Carotte 50g','Tomates concassées 65g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons et la carotte dans l\'huile 5 min.','Ajouter les lentilles vertes et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine poire beurre de cacahuète lait végétal',kcal:347,p:11,g:51,l:11,portions:'2 adultes',ings:['Flocons avoine 56g','Lait végétal 90g','Poire 62g','Beurre cacahuète 11g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la poire coupée en dés.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Sardines riz complet brocoli carotte citron',kcal:523,p:36,g:61,l:15,portions:'2 adultes',ings:['Sardines à l\'huile 113g','Riz complet 68g','Brocoli 73g','Carotte 62g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Égoutter les sardines et râper la carotte.','Assembler riz + sardines + brocoli + carotte, filet de citron.'],note:'Poisson gras riche en oméga-3, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr kiwi noix',kcal:176,p:15,g:16,l:6,portions:'2 adultes',ings:['Skyr 147g','Kiwi 62g','Noix 9g'],steps:['Verser le skyr dans un bol.','Parsemer les noix.','Disposer le kiwi en dés et déguster.'],note:'Kiwi disponible toute l\'année.'},
    {moment:'Dîner',nom:'Lentilles vertes champignons carotte tomates concassées riz basmati',kcal:469,p:22,g:82,l:5,portions:'4 pers.',ings:['Riz basmati 50g','Lentilles vertes 65g','Champignons 55g','Carotte 50g','Tomates concassées 65g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons et la carotte dans l\'huile 5 min.','Ajouter les lentilles vertes et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // SAMEDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine banane cannelle miel yaourt famille',kcal:426,p:21,g:54,l:15,portions:'4 pers.',ings:['Flocons avoine mixés 35g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 75g','Banane 60g','Cannelle 1g','Miel 5g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf, le lait végétal et la cannelle en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, banane et miel.'],note:'Les enfants adorent !'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé patate douce brocoli pâtes complètes',kcal:516,p:27,g:70,l:15,portions:'4 pers.',ings:['Boeuf haché maigre 70g','Pâtes complètes 70g','Patate douce 90g','Brocoli 70g','Huile olive 5g'],steps:['Cuire les pâtes complètes 11 min.','Couper la patate douce en dés, cuire vapeur 10 min avec le brocoli.','Griller les légumes à la poêle 5 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec pâtes et légumes.'],note:'Plat d\'automne du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc poire pomme miel famille',kcal:131,p:9,g:23,l:0,portions:'4 pers.',ings:['Fromage blanc maigre 130g','Poire 55g','Pomme 50g','Miel 5g'],steps:['Couper la poire et la pomme en dés.','Verser sur le fromage blanc.','Arroser de miel et déguster.'],note:'Poire et pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte poireaux tomates riz basmati',kcal:485,p:34,g:71,l:7,portions:'4 pers.',ings:['Cuisses poulet désossées 110g','Riz basmati 75g','Carotte 60g','Poireaux 60g','Tomates concassées 80g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et poireaux, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte d\'automne du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine banane cannelle miel yaourt famille',kcal:426,p:21,g:54,l:15,portions:'4 pers.',ings:['Flocons avoine mixés 35g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 75g','Banane 60g','Cannelle 1g','Miel 5g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf, le lait végétal et la cannelle en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, banane et miel.'],note:'Les enfants adorent !'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé patate douce brocoli pâtes complètes',kcal:516,p:27,g:70,l:15,portions:'4 pers.',ings:['Boeuf haché maigre 70g','Pâtes complètes 70g','Patate douce 90g','Brocoli 70g','Huile olive 5g'],steps:['Cuire les pâtes complètes 11 min.','Couper la patate douce en dés, cuire vapeur 10 min avec le brocoli.','Griller les légumes à la poêle 5 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec pâtes et légumes.'],note:'Plat d\'automne du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc poire pomme miel famille',kcal:131,p:9,g:23,l:0,portions:'4 pers.',ings:['Fromage blanc maigre 130g','Poire 55g','Pomme 50g','Miel 5g'],steps:['Couper la poire et la pomme en dés.','Verser sur le fromage blanc.','Arroser de miel et déguster.'],note:'Poire et pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte poireaux tomates riz basmati',kcal:485,p:34,g:71,l:7,portions:'4 pers.',ings:['Cuisses poulet désossées 110g','Riz basmati 75g','Carotte 60g','Poireaux 60g','Tomates concassées 80g','Huile olive 5g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et poireaux, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte d\'automne du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // DIMANCHE
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr pomme poire amandes famille',kcal:338,p:16,g:48,l:9,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 65g','Pomme 45g','Poire 40g','Flocons avoine 35g','Amandes 10g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la pomme et la poire en dés.','Parsemer les flocons et les amandes.','Déguster frais.'],note:'Pomme et poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Blanc poulet four courge butternut brocoli carotte riz complet',kcal:392,p:26,g:57,l:6,portions:'4 pers.',ings:['Blanc poulet 85g','Riz complet 55g','Courge butternut 65g','Brocoli 55g','Carotte 55g','Huile olive 4g','Ail herbes de Provence 2g'],steps:['Préchauffer le four à 200°C.','Cuire le riz complet 20 min.','Couper les légumes en gros dés, disposer dans un plat avec huile + ail + herbes.','Déposer le poulet sur les légumes, assaisonner.','Rôtir 30 min en arrosant à mi-cuisson.','Servir avec le riz.'],note:'Plat du week-end (35 min). Légumes d\'automne de saison.'},
    {moment:'Collation',nom:'Porridge avoine banane beurre de cacahuète famille',kcal:266,p:8,g:40,l:8,portions:'4 pers.',ings:['Flocons avoine 40g','Lait végétal 75g','Banane 45g','Beurre cacahuète 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer la banane et servir tiède.'],note:'Petit-déjeuner énergétique.'},
    {moment:'Dîner',nom:'Soupe-repas pois chiches potiron poireaux tomates concassées riz complet',kcal:415,p:16,g:70,l:7,portions:'4 pers.',ings:['Riz complet 35g','Pois chiches 60g','Potiron 60g','Poireaux 55g','Tomates concassées 85g','Huile olive 3g'],steps:['Faire revenir le potiron et les poireaux émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les pois chiches avec de l\'eau.','Porter à ébullition, cuire 20 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes d\'automne.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr pomme poire amandes famille',kcal:338,p:16,g:48,l:9,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 65g','Pomme 45g','Poire 40g','Flocons avoine 35g','Amandes 10g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la pomme et la poire en dés.','Parsemer les flocons et les amandes.','Déguster frais.'],note:'Pomme et poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Blanc poulet four courge butternut brocoli carotte riz complet',kcal:392,p:26,g:57,l:6,portions:'4 pers.',ings:['Blanc poulet 85g','Riz complet 55g','Courge butternut 65g','Brocoli 55g','Carotte 55g','Huile olive 4g','Ail herbes de Provence 2g'],steps:['Préchauffer le four à 200°C.','Cuire le riz complet 20 min.','Couper les légumes en gros dés, disposer dans un plat avec huile + ail + herbes.','Déposer le poulet sur les légumes, assaisonner.','Rôtir 30 min en arrosant à mi-cuisson.','Servir avec le riz.'],note:'Plat du week-end (35 min). Légumes d\'automne de saison.'},
    {moment:'Collation',nom:'Porridge avoine banane beurre de cacahuète famille',kcal:266,p:8,g:40,l:8,portions:'4 pers.',ings:['Flocons avoine 40g','Lait végétal 75g','Banane 45g','Beurre cacahuète 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer la banane et servir tiède.'],note:'Petit-déjeuner énergétique.'},
    {moment:'Dîner',nom:'Soupe-repas pois chiches potiron poireaux tomates concassées riz complet',kcal:415,p:16,g:70,l:7,portions:'4 pers.',ings:['Riz complet 35g','Pois chiches 60g','Potiron 60g','Poireaux 55g','Tomates concassées 85g','Huile olive 3g'],steps:['Faire revenir le potiron et les poireaux émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les pois chiches avec de l\'eau.','Porter à ébullition, cuire 20 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes d\'automne.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
];



const semaines=[semaine1, semaine2];
const semaineLabels=['Semaine en cours','Semaine suivante'];
