// ╔══════════════════════════════════════════════════════════════╗
// ║  DONNÉES MENUS — mis à jour chaque mardi par cowork          ║
// ║  Ne modifier que semaine1 et semaine2                        ║
// ╚══════════════════════════════════════════════════════════════╝

// ── DONNÉES SEMAINE 1 ──────────────────────────────────────────
const semaine1=[
  // LUNDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr framboises myrtilles graines de chia',kcal:164,p:13,g:19,l:4,portions:'2 adultes',ings:['Skyr 120g','Framboises 50g','Myrtilles 30g','Graines de chia 10g'],steps:['Verser le skyr dans un bol.','Parsemer les graines de chia.','Disposer les framboises et les myrtilles.','Déguster frais.'],note:'Framboises et myrtilles d\'été de saison.'},
    {moment:'Déjeuner',nom:'Blanc poulet pâtes complètes courgette tomates',kcal:354,p:32,g:43,l:6,portions:'2 adultes',ings:['Blanc poulet 100g','Pâtes complètes 55g','Courgette 90g','Tomates 60g','Huile olive 3g'],steps:['Cuire les pâtes complètes 12 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter la courgette en dés, cuire 5 min.','Ajouter les tomates, cuire 2 min et servir avec les pâtes.'],note:'Courgette d\'été de saison.'},
    {moment:'Collation',nom:'Yaourt nature framboises noisettes',kcal:178,p:8,g:14,l:10,portions:'2 adultes',ings:['Yaourt nature 150g','Framboises 50g','Noisettes 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les noisettes.','Disposer les framboises et déguster.'],note:'Framboises d\'été de saison.'},
    {moment:'Dîner',nom:'Lentilles corail courgette poivron tomates concassées riz complet',kcal:384,p:18,g:69,l:4,portions:'4 pers.',ings:['Riz complet 40g','Lentilles corail 55g','Poivron rouge 50g','Courgette 60g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Faire revenir la courgette et le poivron dans l\'huile 5 min.','Ajouter les lentilles corail et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'été 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr framboises myrtilles graines de chia',kcal:213,p:17,g:25,l:5,portions:'2 adultes',ings:['Skyr 155g','Framboises 65g','Myrtilles 40g','Graines de chia 13g'],steps:['Verser le skyr dans un bol.','Parsemer les graines de chia.','Disposer les framboises et les myrtilles.','Déguster frais.'],note:'Framboises et myrtilles d\'été de saison.'},
    {moment:'Déjeuner',nom:'Blanc poulet pâtes complètes courgette tomates',kcal:439,p:40,g:54,l:7,portions:'2 adultes',ings:['Blanc poulet 125g','Pâtes complètes 70g','Courgette 110g','Tomates 75g','Huile olive 4g'],steps:['Cuire les pâtes complètes 12 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter la courgette en dés, cuire 5 min.','Ajouter les tomates, cuire 2 min et servir avec les pâtes.'],note:'Courgette d\'été de saison.'},
    {moment:'Collation',nom:'Yaourt nature framboises noisettes',kcal:216,p:9,g:18,l:12,portions:'2 adultes',ings:['Yaourt nature 180g','Framboises 65g','Noisettes 10g'],steps:['Verser le yaourt dans un bol.','Parsemer les noisettes.','Disposer les framboises et déguster.'],note:'Framboises d\'été de saison.'},
    {moment:'Dîner',nom:'Lentilles corail courgette poivron tomates concassées riz complet',kcal:384,p:18,g:69,l:4,portions:'4 pers.',ings:['Riz complet 40g','Lentilles corail 55g','Poivron rouge 50g','Courgette 60g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Faire revenir la courgette et le poivron dans l\'huile 5 min.','Ajouter les lentilles corail et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'été 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // MARDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine abricots amandes lait végétal',kcal:260,p:9,g:38,l:8,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 80g','Abricots frais 50g','Amandes 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer les abricots coupés en dés.','Disposer les amandes.','Servir tiède.'],note:'Abricots d\'été de saison.'},
    {moment:'Déjeuner',nom:'Saumon riz basmati épinards tomates citron',kcal:463,p:29,g:44,l:19,portions:'2 adultes',ings:['Saumon 110g','Riz basmati 50g','Épinards frais 80g','Tomates 60g','Citron herbes fraîches 1g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Faire tomber les épinards à la poêle 3 min.','Poêler le saumon 4 min de chaque côté.','Ajouter les tomates, cuire 2 min et servir avec riz et épinards, filet de citron.'],note:'Poisson gras riche en oméga-3, épinards de saison.'},
    {moment:'Collation',nom:'Skyr abricots noisettes',kcal:141,p:13,g:11,l:5,portions:'2 adultes',ings:['Skyr 130g','Abricots frais 50g','Noisettes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les noisettes.','Disposer les abricots en dés et déguster.'],note:'Abricots d\'été de saison.'},
    {moment:'Dîner',nom:'Pois chiches aubergine poivron tomates concassées riz basmati',kcal:407,p:15,g:71,l:7,portions:'4 pers.',ings:['Riz basmati 40g','Pois chiches 55g','Aubergine 60g','Poivron rouge 50g','Tomates concassées 60g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Faire revenir l\'aubergine et le poivron dans l\'huile 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'été 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine abricots amandes lait végétal',kcal:343,p:12,g:49,l:11,portions:'2 adultes',ings:['Flocons avoine 65g','Lait végétal 100g','Abricots frais 65g','Amandes 10g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer les abricots coupés en dés.','Disposer les amandes.','Servir tiède.'],note:'Abricots d\'été de saison.'},
    {moment:'Déjeuner',nom:'Saumon riz basmati épinards tomates citron',kcal:592,p:37,g:57,l:24,portions:'2 adultes',ings:['Saumon 140g','Riz basmati 65g','Épinards frais 100g','Tomates 75g','Citron herbes fraîches 1g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire tomber les épinards à la poêle 3 min.','Poêler le saumon 4 min de chaque côté.','Ajouter les tomates, cuire 2 min et servir avec riz et épinards, filet de citron.'],note:'Poisson gras riche en oméga-3, épinards de saison.'},
    {moment:'Collation',nom:'Skyr abricots noisettes',kcal:178,p:17,g:14,l:6,portions:'2 adultes',ings:['Skyr 160g','Abricots frais 65g','Noisettes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les noisettes.','Disposer les abricots en dés et déguster.'],note:'Abricots d\'été de saison.'},
    {moment:'Dîner',nom:'Pois chiches aubergine poivron tomates concassées riz basmati',kcal:407,p:15,g:71,l:7,portions:'4 pers.',ings:['Riz basmati 40g','Pois chiches 55g','Aubergine 60g','Poivron rouge 50g','Tomates concassées 60g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Faire revenir l\'aubergine et le poivron dans l\'huile 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'été 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // MERCREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine pêche skyr lait végétal',kcal:268,p:14,g:44,l:4,portions:'2 adultes',ings:['Flocons avoine 55g','Skyr 70g','Lait végétal 50g','Pêche 70g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper la pêche et incorporer.','Déguster froid.'],note:'Préparer la veille. Pêche d\'été de saison.'},
    {moment:'Déjeuner',nom:'Boeuf maigre riz complet brocoli tomates',kcal:390,p:26,g:49,l:10,portions:'2 adultes',ings:['Boeuf maigre 90g','Riz complet 55g','Brocoli 90g','Tomates 60g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Poêler le boeuf maigre en lanières 5 min dans l\'huile.','Ajouter le brocoli en petits bouquets, cuire 5 min à couvert.','Ajouter les tomates, cuire 2 min et mélanger avec le riz.'],note:'Brocoli de saison.'},
    {moment:'Collation',nom:'Petit suisse pêche miel',kcal:151,p:8,g:14,l:7,portions:'2 adultes',ings:['Petit suisse 100g','Pêche 60g','Miel 5g'],steps:['Couper la pêche en dés.','Verser sur le petit suisse.','Arroser de miel et déguster.'],note:'Pêche d\'été de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade poivron champignons tomates oignon',kcal:234,p:16,g:11,l:14,portions:'4 pers.',ings:['Oeufs 2 pièces','Poivron rouge 50g','Champignons 70g','Tomates 60g','Oignon 30g','Huile olive 4g'],steps:['Émincer l\'oignon, faire revenir avec le poivron et les champignons dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs et verser sur les légumes.','Cuire à feu doux 4 min et servir.'],note:'Pipérade rapide d\'été 16 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine pêche skyr lait végétal',kcal:354,p:18,g:57,l:6,portions:'2 adultes',ings:['Flocons avoine 70g','Skyr 90g','Lait végétal 65g','Pêche 90g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper la pêche et incorporer.','Déguster froid.'],note:'Préparer la veille. Pêche d\'été de saison.'},
    {moment:'Déjeuner',nom:'Boeuf maigre riz complet brocoli tomates',kcal:497,p:33,g:62,l:13,portions:'2 adultes',ings:['Boeuf maigre 115g','Riz complet 70g','Brocoli 110g','Tomates 75g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Poêler le boeuf maigre en lanières 5 min dans l\'huile.','Ajouter le brocoli en petits bouquets, cuire 5 min à couvert.','Ajouter les tomates, cuire 2 min et mélanger avec le riz.'],note:'Brocoli de saison.'},
    {moment:'Collation',nom:'Petit suisse pêche miel',kcal:193,p:10,g:18,l:9,portions:'2 adultes',ings:['Petit suisse 130g','Pêche 80g','Miel 6g'],steps:['Couper la pêche en dés.','Verser sur le petit suisse.','Arroser de miel et déguster.'],note:'Pêche d\'été de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade poivron champignons tomates oignon',kcal:234,p:16,g:11,l:14,portions:'4 pers.',ings:['Oeufs 2 pièces','Poivron rouge 50g','Champignons 70g','Tomates 60g','Oignon 30g','Huile olive 4g'],steps:['Émincer l\'oignon, faire revenir avec le poivron et les champignons dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs et verser sur les légumes.','Cuire à feu doux 4 min et servir.'],note:'Pipérade rapide d\'été 16 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // JEUDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature myrtilles flocons noix',kcal:296,p:12,g:35,l:12,portions:'2 adultes',ings:['Yaourt nature 150g','Myrtilles 60g','Flocons avoine 30g','Noix 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Disposer les myrtilles et déguster frais.'],note:'Myrtilles d\'été de saison.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz basmati poireaux tomates',kcal:399,p:25,g:50,l:11,portions:'2 adultes',ings:['Cuisses poulet désossées 95g','Riz basmati 55g','Poireaux 80g','Tomates 60g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les poireaux émincés, cuire 5 min.','Ajouter les tomates, cuire 2 min et servir sur le riz.'],note:'Poireaux de saison.'},
    {moment:'Collation',nom:'Fromage blanc framboises miel',kcal:92,p:9,g:14,l:0,portions:'2 adultes',ings:['Fromage blanc maigre 120g','Framboises 50g','Miel 5g'],steps:['Verser le fromage blanc dans un bol.','Disposer les framboises.','Arroser de miel et déguster.'],note:'Framboises d\'été de saison.'},
    {moment:'Dîner',nom:'Haricots rouges courgette poivron tomates concassées riz complet',kcal:385,p:17,g:68,l:5,portions:'4 pers.',ings:['Riz complet 40g','Haricots rouges 55g','Courgette 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Faire revenir la courgette et le poivron dans l\'huile 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'été 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature myrtilles flocons noix',kcal:384,p:15,g:45,l:16,portions:'2 adultes',ings:['Yaourt nature 185g','Myrtilles 75g','Flocons avoine 40g','Noix 10g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Disposer les myrtilles et déguster frais.'],note:'Myrtilles d\'été de saison.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz basmati poireaux tomates',kcal:506,p:31,g:64,l:14,portions:'2 adultes',ings:['Cuisses poulet désossées 120g','Riz basmati 70g','Poireaux 100g','Tomates 75g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les poireaux émincés, cuire 5 min.','Ajouter les tomates, cuire 2 min et servir sur le riz.'],note:'Poireaux de saison.'},
    {moment:'Collation',nom:'Fromage blanc framboises miel',kcal:121,p:11,g:17,l:1,portions:'2 adultes',ings:['Fromage blanc maigre 150g','Framboises 65g','Miel 6g'],steps:['Verser le fromage blanc dans un bol.','Disposer les framboises.','Arroser de miel et déguster.'],note:'Framboises d\'été de saison.'},
    {moment:'Dîner',nom:'Haricots rouges courgette poivron tomates concassées riz complet',kcal:385,p:17,g:68,l:5,portions:'4 pers.',ings:['Riz complet 40g','Haricots rouges 55g','Courgette 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Faire revenir la courgette et le poivron dans l\'huile 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'été 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // VENDREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine pêche beurre cacahuète lait végétal',kcal:260,p:9,g:38,l:8,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 80g','Pêche 50g','Beurre cacahuète 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la pêche coupée en dés.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Pêche d\'été de saison.'},
    {moment:'Déjeuner',nom:'Maquereau fumé riz complet fenouil tomates citron',kcal:397,p:26,g:44,l:13,portions:'2 adultes',ings:['Maquereau fumé en boîte 90g','Riz complet 50g','Fenouil 60g','Tomates 60g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Émietter le maquereau fumé.','Couper le fenouil et les tomates en dés.','Assembler riz + maquereau + fenouil + tomates, filet de citron.'],note:'Poisson gras riche en oméga-3, fenouil d\'été de saison.'},
    {moment:'Collation',nom:'Skyr pêche amandes',kcal:140,p:14,g:12,l:4,portions:'2 adultes',ings:['Skyr 130g','Pêche 60g','Amandes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Disposer la pêche en dés et déguster.'],note:'Pêche d\'été de saison.'},
    {moment:'Dîner',nom:'Lentilles vertes champignons poivron tomates concassées riz basmati',kcal:384,p:19,g:68,l:4,portions:'4 pers.',ings:['Riz basmati 40g','Lentilles vertes 55g','Champignons 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons et le poivron dans l\'huile 5 min.','Ajouter les lentilles vertes et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien riche en fer 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine pêche beurre cacahuète lait végétal',kcal:347,p:12,g:50,l:11,portions:'2 adultes',ings:['Flocons avoine 65g','Lait végétal 100g','Pêche 65g','Beurre cacahuète 10g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la pêche coupée en dés.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Pêche d\'été de saison.'},
    {moment:'Déjeuner',nom:'Maquereau fumé riz complet fenouil tomates citron',kcal:500,p:33,g:56,l:16,portions:'2 adultes',ings:['Maquereau fumé en boîte 113g','Riz complet 65g','Fenouil 75g','Tomates 75g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Émietter le maquereau fumé.','Couper le fenouil et les tomates en dés.','Assembler riz + maquereau + fenouil + tomates, filet de citron.'],note:'Poisson gras riche en oméga-3, fenouil d\'été de saison.'},
    {moment:'Collation',nom:'Skyr pêche amandes',kcal:173,p:17,g:15,l:5,portions:'2 adultes',ings:['Skyr 160g','Pêche 80g','Amandes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Disposer la pêche en dés et déguster.'],note:'Pêche d\'été de saison.'},
    {moment:'Dîner',nom:'Lentilles vertes champignons poivron tomates concassées riz basmati',kcal:384,p:19,g:68,l:4,portions:'4 pers.',ings:['Riz basmati 40g','Lentilles vertes 55g','Champignons 60g','Poivron rouge 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons et le poivron dans l\'huile 5 min.','Ajouter les lentilles vertes et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien riche en fer 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // SAMEDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine myrtilles miel yaourt famille',kcal:277,p:13,g:36,l:9,portions:'4 pers.',ings:['Flocons avoine mixés 30g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 50g','Myrtilles 30g','Miel 5g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf et le lait végétal en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, myrtilles et miel.'],note:'Les enfants adorent ! Myrtilles d\'été de saison.'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé poivron carotte riz complet',kcal:375,p:17,g:52,l:11,portions:'4 pers.',ings:['Boeuf haché maigre 56g','Riz complet 55g','Poivron rouge 90g','Carotte 60g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Couper le poivron et la carotte.','Griller les légumes à la poêle 8 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec riz et légumes.'],note:'Plat estival du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc myrtilles framboises miel famille',kcal:101,p:8,g:15,l:1,portions:'4 pers.',ings:['Fromage blanc maigre 100g','Myrtilles 30g','Framboises 30g','Miel 5g'],steps:['Verser le fromage blanc dans un bol.','Disposer les myrtilles et les framboises.','Arroser de miel et déguster.'],note:'Myrtilles et framboises d\'été de saison.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte poireaux tomates riz basmati',kcal:407,p:22,g:55,l:11,portions:'4 pers.',ings:['Cuisses poulet désossées 82g','Riz basmati 55g','Carotte 60g','Poireaux 60g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et poireaux en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte d\'été du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine myrtilles miel yaourt famille',kcal:277,p:13,g:36,l:9,portions:'4 pers.',ings:['Flocons avoine mixés 30g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 50g','Myrtilles 30g','Miel 5g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf et le lait végétal en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, myrtilles et miel.'],note:'Les enfants adorent ! Myrtilles d\'été de saison.'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé poivron carotte riz complet',kcal:375,p:17,g:52,l:11,portions:'4 pers.',ings:['Boeuf haché maigre 56g','Riz complet 55g','Poivron rouge 90g','Carotte 60g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Couper le poivron et la carotte.','Griller les légumes à la poêle 8 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec riz et légumes.'],note:'Plat estival du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc myrtilles framboises miel famille',kcal:101,p:8,g:15,l:1,portions:'4 pers.',ings:['Fromage blanc maigre 100g','Myrtilles 30g','Framboises 30g','Miel 5g'],steps:['Verser le fromage blanc dans un bol.','Disposer les myrtilles et les framboises.','Arroser de miel et déguster.'],note:'Myrtilles et framboises d\'été de saison.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte poireaux tomates riz basmati',kcal:407,p:22,g:55,l:11,portions:'4 pers.',ings:['Cuisses poulet désossées 82g','Riz basmati 55g','Carotte 60g','Poireaux 60g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et poireaux en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte d\'été du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // DIMANCHE
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr banane framboises noix famille',kcal:337,p:16,g:48,l:9,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 70g','Banane 50g','Framboises 25g','Flocons avoine 30g','Noix 8g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la banane en rondelles.','Parsemer les flocons et les noix.','Disposer les framboises et déguster frais.'],note:'Framboises d\'été de saison.'},
    {moment:'Déjeuner',nom:'Blanc poulet cocotte courgette poivron tomates riz basmati',kcal:349,p:25,g:51,l:5,portions:'4 pers.',ings:['Blanc poulet 82g','Riz basmati 55g','Courgette 90g','Poivron rouge 60g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Dorer le poulet 5 min de chaque côté dans l\'huile.','Ajouter courgette et poivron en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 10 min à couvert et servir sur le riz.'],note:'Cocotte d\'été du dimanche (30 min). Légumes de saison.'},
    {moment:'Collation',nom:'Porridge avoine myrtilles beurre cacahuète famille',kcal:228,p:8,g:31,l:8,portions:'4 pers.',ings:['Flocons avoine 40g','Lait végétal 80g','Myrtilles 30g','Beurre cacahuète 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer les myrtilles et servir tiède.'],note:'Myrtilles d\'été de saison.'},
    {moment:'Dîner',nom:'Lentilles corail poireaux champignons tomates concassées riz complet',kcal:384,p:20,g:67,l:4,portions:'4 pers.',ings:['Riz complet 35g','Lentilles corail 55g','Poireaux 60g','Champignons 60g','Tomates concassées 90g','Huile olive 3g'],steps:['Faire revenir les poireaux et les champignons émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les lentilles corail avec de l\'eau.','Porter à ébullition, cuire 15 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes d\'été.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr banane framboises noix famille',kcal:337,p:16,g:48,l:9,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 70g','Banane 50g','Framboises 25g','Flocons avoine 30g','Noix 8g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la banane en rondelles.','Parsemer les flocons et les noix.','Disposer les framboises et déguster frais.'],note:'Framboises d\'été de saison.'},
    {moment:'Déjeuner',nom:'Blanc poulet cocotte courgette poivron tomates riz basmati',kcal:349,p:25,g:51,l:5,portions:'4 pers.',ings:['Blanc poulet 82g','Riz basmati 55g','Courgette 90g','Poivron rouge 60g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Dorer le poulet 5 min de chaque côté dans l\'huile.','Ajouter courgette et poivron en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 10 min à couvert et servir sur le riz.'],note:'Cocotte d\'été du dimanche (30 min). Légumes de saison.'},
    {moment:'Collation',nom:'Porridge avoine myrtilles beurre cacahuète famille',kcal:228,p:8,g:31,l:8,portions:'4 pers.',ings:['Flocons avoine 40g','Lait végétal 80g','Myrtilles 30g','Beurre cacahuète 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer les myrtilles et servir tiède.'],note:'Myrtilles d\'été de saison.'},
    {moment:'Dîner',nom:'Lentilles corail poireaux champignons tomates concassées riz complet',kcal:384,p:20,g:67,l:4,portions:'4 pers.',ings:['Riz complet 35g','Lentilles corail 55g','Poireaux 60g','Champignons 60g','Tomates concassées 90g','Huile olive 3g'],steps:['Faire revenir les poireaux et les champignons émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les lentilles corail avec de l\'eau.','Porter à ébullition, cuire 15 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes d\'été.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
];

const semaine2=[
  // LUNDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr pomme poire flocons amandes',kcal:255,p:16,g:35,l:6,portions:'2 adultes',ings:['Skyr 120g','Pomme 60g','Poire 40g','Flocons avoine 25g','Amandes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les amandes.','Couper la pomme et la poire en dés.','Disposer sur le skyr et déguster.'],note:'Pomme et poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Blanc poulet riz complet brocoli champignons',kcal:369,p:31,g:48,l:5,portions:'2 adultes',ings:['Blanc poulet 100g','Riz complet 55g','Brocoli 80g','Champignons 60g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter les champignons émincés, cuire 4 min et servir avec riz et brocoli.'],note:'Brocoli et champignons d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt nature pomme amandes',kcal:171,p:8,g:18,l:8,portions:'2 adultes',ings:['Yaourt nature 150g','Pomme 70g','Amandes 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les amandes.','Couper la pomme en dés et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Lentilles vertes potiron poireaux tomates concassées riz basmati',kcal:392,p:18,g:70,l:4,portions:'4 pers.',ings:['Riz basmati 40g','Lentilles vertes 55g','Potiron 60g','Poireaux 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Cuire les lentilles vertes 20 min à l\'eau bouillante.','Faire revenir le potiron et les poireaux dans l\'huile 6 min.','Ajouter les tomates concassées et les lentilles cuites, mijoter 4 min et servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr pomme poire flocons amandes',kcal:333,p:20,g:47,l:7,portions:'2 adultes',ings:['Skyr 155g','Pomme 80g','Poire 55g','Flocons avoine 33g','Amandes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les flocons et les amandes.','Couper la pomme et la poire en dés.','Disposer sur le skyr et déguster.'],note:'Pomme et poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Blanc poulet riz complet brocoli champignons',kcal:467,p:39,g:63,l:6,portions:'2 adultes',ings:['Blanc poulet 125g','Riz complet 70g','Brocoli 95g','Champignons 75g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Poêler le poulet en lanières 7 min dans l\'huile.','Ajouter les champignons émincés, cuire 4 min et servir avec riz et brocoli.'],note:'Brocoli et champignons d\'automne de saison.'},
    {moment:'Collation',nom:'Yaourt nature pomme amandes',kcal:217,p:10,g:22,l:11,portions:'2 adultes',ings:['Yaourt nature 180g','Pomme 90g','Amandes 11g'],steps:['Verser le yaourt dans un bol.','Parsemer les amandes.','Couper la pomme en dés et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Lentilles vertes potiron poireaux tomates concassées riz basmati',kcal:392,p:18,g:70,l:4,portions:'4 pers.',ings:['Riz basmati 40g','Lentilles vertes 55g','Potiron 60g','Poireaux 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Cuire les lentilles vertes 20 min à l\'eau bouillante.','Faire revenir le potiron et les poireaux dans l\'huile 6 min.','Ajouter les tomates concassées et les lentilles cuites, mijoter 4 min et servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // MARDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine pomme amandes lait végétal',kcal:294,p:9,g:44,l:9,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 80g','Pomme 60g','Amandes 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la pomme coupée en dés.','Disposer les amandes.','Servir tiède.'],note:'Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cabillaud riz complet épinards tomates citron',kcal:355,p:30,g:46,l:5,portions:'2 adultes',ings:['Cabillaud 130g','Riz complet 55g','Épinards frais 80g','Tomates 60g','Huile olive 3g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Faire tomber les épinards à la poêle 3 min.','Poêler le cabillaud 6 min à couvert dans l\'huile.','Ajouter les tomates, cuire 2 min et servir avec riz et épinards, filet de citron.'],note:'Poisson maigre, épinards de saison.'},
    {moment:'Collation',nom:'Skyr pomme noisettes',kcal:152,p:13,g:14,l:5,portions:'2 adultes',ings:['Skyr 130g','Pomme 60g','Noisettes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les noisettes.','Disposer la pomme en dés et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Pois chiches courge butternut poireaux tomates concassées riz basmati cumin',kcal:420,p:16,g:74,l:7,portions:'4 pers.',ings:['Riz basmati 40g','Pois chiches 55g','Courge butternut 60g','Poireaux 50g','Tomates concassées 60g','Huile olive 3g','Cumin 1g'],steps:['Cuire le riz basmati 12 min.','Faire revenir la courge butternut et les poireaux dans l\'huile avec le cumin 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine pomme amandes lait végétal',kcal:379,p:11,g:57,l:11,portions:'2 adultes',ings:['Flocons avoine 65g','Lait végétal 100g','Pomme 80g','Amandes 10g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la pomme coupée en dés.','Disposer les amandes.','Servir tiède.'],note:'Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cabillaud riz complet épinards tomates citron',kcal:440,p:36,g:61,l:6,portions:'2 adultes',ings:['Cabillaud 150g','Riz complet 70g','Épinards frais 100g','Tomates 75g','Huile olive 4g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Faire tomber les épinards à la poêle 3 min.','Poêler le cabillaud 6 min à couvert dans l\'huile.','Ajouter les tomates, cuire 2 min et servir avec riz et épinards, filet de citron.'],note:'Poisson maigre, épinards de saison.'},
    {moment:'Collation',nom:'Skyr pomme noisettes',kcal:191,p:16,g:18,l:6,portions:'2 adultes',ings:['Skyr 160g','Pomme 80g','Noisettes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les noisettes.','Disposer la pomme en dés et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Pois chiches courge butternut poireaux tomates concassées riz basmati cumin',kcal:420,p:16,g:74,l:7,portions:'4 pers.',ings:['Riz basmati 40g','Pois chiches 55g','Courge butternut 60g','Poireaux 50g','Tomates concassées 60g','Huile olive 3g','Cumin 1g'],steps:['Cuire le riz basmati 12 min.','Faire revenir la courge butternut et les poireaux dans l\'huile avec le cumin 6 min.','Ajouter les pois chiches et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // MERCREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine poire skyr lait végétal',kcal:298,p:14,g:50,l:5,portions:'2 adultes',ings:['Flocons avoine 55g','Skyr 70g','Lait végétal 50g','Poire 70g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper la poire et incorporer.','Déguster froid.'],note:'Préparer la veille. Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Boeuf maigre riz complet champignons carotte',kcal:394,p:25,g:48,l:10,portions:'2 adultes',ings:['Boeuf maigre 90g','Riz complet 55g','Champignons 70g','Carotte 60g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Poêler le boeuf maigre en lanières 5 min dans l\'huile.','Ajouter les champignons et la carotte râpée, cuire 5 min.','Mélanger avec le riz et servir.'],note:'Champignons et carotte d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse poire miel',kcal:159,p:7,g:17,l:7,portions:'2 adultes',ings:['Petit suisse 100g','Poire 60g','Miel 5g'],steps:['Couper la poire en dés.','Verser sur le petit suisse.','Arroser de miel et déguster.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade poireaux carotte tomates oignon',kcal:237,p:15,g:14,l:14,portions:'4 pers.',ings:['Oeufs 2 pièces','Poireaux 50g','Carotte 50g','Tomates 60g','Oignon 30g','Huile olive 4g'],steps:['Émincer l\'oignon, faire revenir avec les poireaux et la carotte dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs et verser sur les légumes.','Cuire à feu doux 4 min et servir.'],note:'Pipérade d\'automne rapide 16 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine poire skyr lait végétal',kcal:381,p:18,g:64,l:6,portions:'2 adultes',ings:['Flocons avoine 70g','Skyr 90g','Lait végétal 65g','Poire 90g'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin, couper la poire et incorporer.','Déguster froid.'],note:'Préparer la veille. Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Boeuf maigre riz complet champignons carotte',kcal:503,p:33,g:63,l:13,portions:'2 adultes',ings:['Boeuf maigre 115g','Riz complet 70g','Champignons 90g','Carotte 75g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Poêler le boeuf maigre en lanières 5 min dans l\'huile.','Ajouter les champignons et la carotte râpée, cuire 5 min.','Mélanger avec le riz et servir.'],note:'Champignons et carotte d\'automne de saison.'},
    {moment:'Collation',nom:'Petit suisse poire miel',kcal:207,p:9,g:22,l:9,portions:'2 adultes',ings:['Petit suisse 130g','Poire 80g','Miel 6g'],steps:['Couper la poire en dés.','Verser sur le petit suisse.','Arroser de miel et déguster.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Oeufs pipérade poireaux carotte tomates oignon',kcal:237,p:15,g:14,l:14,portions:'4 pers.',ings:['Oeufs 2 pièces','Poireaux 50g','Carotte 50g','Tomates 60g','Oignon 30g','Huile olive 4g'],steps:['Émincer l\'oignon, faire revenir avec les poireaux et la carotte dans l\'huile 6 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs et verser sur les légumes.','Cuire à feu doux 4 min et servir.'],note:'Pipérade d\'automne rapide 16 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // JEUDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature pomme flocons noix',kcal:285,p:11,g:36,l:12,portions:'2 adultes',ings:['Yaourt nature 150g','Pomme 70g','Flocons avoine 30g','Noix 8g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Disposer la pomme en dés et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz basmati champignons carotte',kcal:364,p:29,g:50,l:5,portions:'2 adultes',ings:['Cuisses poulet désossées 95g','Riz basmati 55g','Champignons 70g','Carotte 60g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les champignons et la carotte, cuire 5 min.','Servir sur le riz.'],note:'Champignons et carotte d\'automne de saison.'},
    {moment:'Collation',nom:'Fromage blanc pomme miel',kcal:100,p:8,g:16,l:0,portions:'2 adultes',ings:['Fromage blanc maigre 120g','Pomme 60g','Miel 5g'],steps:['Verser le fromage blanc dans un bol.','Disposer la pomme en dés.','Arroser de miel et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Haricots rouges potiron poireaux tomates concassées riz complet',kcal:394,p:17,g:70,l:5,portions:'4 pers.',ings:['Riz complet 40g','Haricots rouges 55g','Potiron 60g','Poireaux 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Faire revenir le potiron et les poireaux dans l\'huile 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature pomme flocons noix',kcal:365,p:14,g:47,l:15,portions:'2 adultes',ings:['Yaourt nature 185g','Pomme 90g','Flocons avoine 40g','Noix 10g'],steps:['Verser le yaourt dans un bol.','Parsemer les flocons et les noix.','Disposer la pomme en dés et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cuisses poulet riz basmati champignons carotte',kcal:463,p:37,g:63,l:6,portions:'2 adultes',ings:['Cuisses poulet désossées 120g','Riz basmati 70g','Champignons 90g','Carotte 75g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Poêler les cuisses de poulet 8 min dans l\'huile.','Ajouter les champignons et la carotte, cuire 5 min.','Servir sur le riz.'],note:'Champignons et carotte d\'automne de saison.'},
    {moment:'Collation',nom:'Fromage blanc pomme miel',kcal:127,p:11,g:21,l:0,portions:'2 adultes',ings:['Fromage blanc maigre 150g','Pomme 80g','Miel 6g'],steps:['Verser le fromage blanc dans un bol.','Disposer la pomme en dés.','Arroser de miel et déguster.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Haricots rouges potiron poireaux tomates concassées riz complet',kcal:394,p:17,g:70,l:5,portions:'4 pers.',ings:['Riz complet 40g','Haricots rouges 55g','Potiron 60g','Poireaux 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Faire revenir le potiron et les poireaux dans l\'huile 5 min.','Ajouter les haricots rouges et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // VENDREDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine poire beurre cacahuète lait végétal',kcal:292,p:9,g:44,l:9,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 80g','Poire 50g','Beurre cacahuète 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la poire coupée en dés.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Thon riz complet brocoli carotte citron',kcal:380,p:32,g:50,l:5,portions:'2 adultes',ings:['Thon en boîte 100g','Riz complet 55g','Brocoli 60g','Carotte 60g','Huile olive 3g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Égoutter le thon et couper la carotte en dés.','Assembler riz + thon + brocoli + carotte, filet de citron.'],note:'Poisson maigre, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr poire amandes',kcal:145,p:13,g:13,l:4,portions:'2 adultes',ings:['Skyr 130g','Poire 50g','Amandes 8g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Disposer la poire en dés et déguster.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Lentilles corail champignons carotte tomates concassées riz basmati',kcal:400,p:19,g:71,l:4,portions:'4 pers.',ings:['Riz basmati 40g','Lentilles corail 55g','Champignons 60g','Carotte 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons et la carotte dans l\'huile 5 min.','Ajouter les lentilles corail et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine poire beurre cacahuète lait végétal',kcal:376,p:12,g:57,l:11,portions:'2 adultes',ings:['Flocons avoine 65g','Lait végétal 100g','Poire 65g','Beurre cacahuète 10g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer la poire coupée en dés.','Disposer le beurre de cacahuète.','Servir tiède.'],note:'Poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Thon riz complet brocoli carotte citron',kcal:487,p:42,g:66,l:6,portions:'2 adultes',ings:['Thon en boîte 130g','Riz complet 70g','Brocoli 75g','Carotte 75g','Huile olive 4g','Citron herbes fraîches 1g'],steps:['Cuire le riz complet 20 min.','Cuire le brocoli vapeur 7 min.','Égoutter le thon et couper la carotte en dés.','Assembler riz + thon + brocoli + carotte, filet de citron.'],note:'Poisson maigre, brocoli d\'automne de saison.'},
    {moment:'Collation',nom:'Skyr poire amandes',kcal:181,p:17,g:17,l:5,portions:'2 adultes',ings:['Skyr 160g','Poire 65g','Amandes 10g'],steps:['Verser le skyr dans un bol.','Parsemer les amandes.','Disposer la poire en dés et déguster.'],note:'Poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Lentilles corail champignons carotte tomates concassées riz basmati',kcal:400,p:19,g:71,l:4,portions:'4 pers.',ings:['Riz basmati 40g','Lentilles corail 55g','Champignons 60g','Carotte 50g','Tomates concassées 70g','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Faire revenir les champignons et la carotte dans l\'huile 5 min.','Ajouter les lentilles corail et les tomates concassées, mijoter 6 min.','Servir sur le riz.'],note:'Plat végétarien d\'automne 17 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:126,p:3,g:7,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ]},
  // SAMEDI
  {f:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine pomme cannelle miel yaourt famille',kcal:284,p:13,g:40,l:9,portions:'4 pers.',ings:['Flocons avoine mixés 30g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 50g','Pomme 50g','Cannelle 1g','Miel 5g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf, le lait végétal et la cannelle en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, pomme et miel.'],note:'Les enfants adorent ! Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé courge butternut carotte riz complet',kcal:394,p:17,g:56,l:11,portions:'4 pers.',ings:['Boeuf haché maigre 56g','Riz complet 55g','Courge butternut 90g','Carotte 60g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Couper la courge butternut et la carotte en dés.','Griller les légumes à la poêle 8 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec riz et légumes.'],note:'Plat d\'automne du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc pomme poire miel famille',kcal:109,p:7,g:20,l:0,portions:'4 pers.',ings:['Fromage blanc maigre 100g','Pomme 50g','Poire 40g','Miel 5g'],steps:['Couper la pomme et la poire en dés.','Verser sur le fromage blanc.','Arroser de miel et déguster.'],note:'Pomme et poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte potiron tomates riz basmati',kcal:371,p:25,g:54,l:5,portions:'4 pers.',ings:['Cuisses poulet désossées 82g','Riz basmati 55g','Carotte 60g','Potiron 60g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et potiron en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte d\'automne du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine pomme cannelle miel yaourt famille',kcal:284,p:13,g:40,l:9,portions:'4 pers.',ings:['Flocons avoine mixés 30g','Oeufs 1 pièce','Lait végétal 30g','Yaourt fruits mixé 50g','Pomme 50g','Cannelle 1g','Miel 5g'],steps:['Mixer les flocons en poudre fine.','Mélanger avec l\'oeuf, le lait végétal et la cannelle en pâte lisse.','Cuire les pancakes 3 min/face à feu moyen.','Servir avec yaourt, pomme et miel.'],note:'Les enfants adorent ! Pomme d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Boeuf haché maigre grillé courge butternut carotte riz complet',kcal:394,p:17,g:56,l:11,portions:'4 pers.',ings:['Boeuf haché maigre 56g','Riz complet 55g','Courge butternut 90g','Carotte 60g','Huile olive 4g'],steps:['Cuire le riz complet 20 min.','Couper la courge butternut et la carotte en dés.','Griller les légumes à la poêle 8 min avec l\'huile.','Griller le boeuf haché en steaks 3-4 min/face et servir avec riz et légumes.'],note:'Plat d\'automne du week-end (28 min). Légumes de saison.'},
    {moment:'Collation',nom:'Fromage blanc pomme poire miel famille',kcal:109,p:7,g:20,l:0,portions:'4 pers.',ings:['Fromage blanc maigre 100g','Pomme 50g','Poire 40g','Miel 5g'],steps:['Couper la pomme et la poire en dés.','Verser sur le fromage blanc.','Arroser de miel et déguster.'],note:'Pomme et poire d\'automne de saison.'},
    {moment:'Dîner',nom:'Cuisses poulet cocotte carotte potiron tomates riz basmati',kcal:371,p:25,g:54,l:5,portions:'4 pers.',ings:['Cuisses poulet désossées 82g','Riz basmati 55g','Carotte 60g','Potiron 60g','Tomates concassées 70g','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Dorer les cuisses de poulet 5 min de chaque côté dans l\'huile.','Ajouter carotte et potiron en dés, cuire 6 min.','Ajouter les tomates concassées, mijoter 15 min à couvert et servir sur le riz.'],note:'Cocotte d\'automne du week-end (30 min). Légumes de saison.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
  // DIMANCHE
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr pomme poire noix famille',kcal:314,p:15,g:44,l:9,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 70g','Pomme 40g','Poire 35g','Flocons avoine 30g','Noix 8g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la pomme et la poire en dés.','Parsemer les flocons et les noix.','Déguster frais.'],note:'Pomme et poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cuisses poulet four courge butternut brocoli carotte riz complet',kcal:395,p:26,g:58,l:6,portions:'4 pers.',ings:['Cuisses poulet désossées 82g','Riz complet 55g','Courge butternut 70g','Brocoli 60g','Carotte 60g','Huile olive 4g','Ail 1g','Herbes de Provence 1g'],steps:['Préchauffer le four à 200°C.','Cuire le riz complet 20 min.','Couper les légumes en gros dés, disposer dans un plat avec huile + ail + herbes.','Déposer les cuisses de poulet sur les légumes, assaisonner.','Rôtir 30 min en arrosant à mi-cuisson.','Servir avec le riz.'],note:'Plat du week-end (35 min). Légumes d\'automne de saison.'},
    {moment:'Collation',nom:'Porridge avoine pomme beurre cacahuète famille',kcal:249,p:8,g:36,l:8,portions:'4 pers.',ings:['Flocons avoine 40g','Lait végétal 80g','Pomme 40g','Beurre cacahuète 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer la pomme et servir tiède.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Soupe-repas lentilles corail potiron poireaux tomates concassées riz complet',kcal:386,p:18,g:69,l:4,portions:'4 pers.',ings:['Riz complet 35g','Lentilles corail 55g','Potiron 60g','Poireaux 60g','Tomates concassées 90g','Huile olive 3g'],steps:['Faire revenir le potiron et les poireaux émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les lentilles corail avec de l\'eau.','Porter à ébullition, cuire 15 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes d\'automne.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol yaourt skyr pomme poire noix famille',kcal:314,p:15,g:44,l:9,portions:'4 pers.',ings:['Skyr 80g','Yaourt fruits mixé 70g','Pomme 40g','Poire 35g','Flocons avoine 30g','Noix 8g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la pomme et la poire en dés.','Parsemer les flocons et les noix.','Déguster frais.'],note:'Pomme et poire d\'automne de saison.'},
    {moment:'Déjeuner',nom:'Cuisses poulet four courge butternut brocoli carotte riz complet',kcal:395,p:26,g:58,l:6,portions:'4 pers.',ings:['Cuisses poulet désossées 82g','Riz complet 55g','Courge butternut 70g','Brocoli 60g','Carotte 60g','Huile olive 4g','Ail 1g','Herbes de Provence 1g'],steps:['Préchauffer le four à 200°C.','Cuire le riz complet 20 min.','Couper les légumes en gros dés, disposer dans un plat avec huile + ail + herbes.','Déposer les cuisses de poulet sur les légumes, assaisonner.','Rôtir 30 min en arrosant à mi-cuisson.','Servir avec le riz.'],note:'Plat du week-end (35 min). Légumes d\'automne de saison.'},
    {moment:'Collation',nom:'Porridge avoine pomme beurre cacahuète famille',kcal:249,p:8,g:36,l:8,portions:'4 pers.',ings:['Flocons avoine 40g','Lait végétal 80g','Pomme 40g','Beurre cacahuète 8g'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Incorporer le beurre de cacahuète.','Disposer la pomme et servir tiède.'],note:'Pomme d\'automne de saison.'},
    {moment:'Dîner',nom:'Soupe-repas lentilles corail potiron poireaux tomates concassées riz complet',kcal:386,p:18,g:69,l:4,portions:'4 pers.',ings:['Riz complet 35g','Lentilles corail 55g','Potiron 60g','Poireaux 60g','Tomates concassées 90g','Huile olive 3g'],steps:['Faire revenir le potiron et les poireaux émincés dans l\'huile 4 min.','Ajouter les tomates concassées, le riz complet et les lentilles corail avec de l\'eau.','Porter à ébullition, cuire 15 min.','Servir chaud.'],note:'Soupe-repas du dimanche soir, végétarienne. Légumes d\'automne.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:80,p:1,g:7,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ]},
];


const semaines=[semaine1, semaine2];
const semaineLabels=['Semaine en cours','Semaine suivante'];
