// Généré automatiquement depuis reference.txt par run_hebdo.py — NE PAS MODIFIER À LA MAIN
// Généré le 2026-09-29 — 111 prix (v = vérifié, sinon estimation)
const PRIX_REF = {
  'Blanc poulet': {p: 16.97, u: 'kg', v: true},
  'Cuisses poulet désossées': {p: 14.36, u: 'kg', v: true},
  'Boeuf maigre': {p: 16.23, u: 'kg', v: true},
  'Boeuf haché maigre': {p: 20.69, u: 'kg', v: true},
  'Dinde filet': {p: 9.18, u: 'kg', v: false},
  'Dinde tranches': {p: 10.94, u: 'kg', v: false},
  'Saumon': {p: 23.59, u: 'kg', v: true},
  'Cabillaud': {p: 16.7, u: 'kg', v: true},
  'Thon en boîte': {p: 12.56, u: 'kg', v: true},
  'Maquereau fumé': {p: 6.12, u: 'kg', v: false},
  "Sardines à l'huile": {p: 5.1, u: 'kg', v: false},
  'Oeufs': {p: 0.26, u: 'pièce', v: true},
  'Skyr': {p: 4.21, u: 'kg', v: true},
  'Yaourt nature': {p: 2.24, u: 'kg', v: false},
  'Yaourt fruits mixé': {p: 3.08, u: 'kg', v: true},
  'Petit suisse': {p: 5.1, u: 'kg', v: false},
  'Fromage blanc maigre': {p: 3.57, u: 'kg', v: false},
  'Gruyère': {p: 11.22, u: 'kg', v: false},
  'Parmesan': {p: 24.04, u: 'kg', v: true},
  'Lait végétal': {p: 1.67, u: 'L', v: true},
  'Lait de coco': {p: 3.06, u: 'L', v: false},
  'Crème légère': {p: 4.08, u: 'kg', v: false},
  'Riz complet': {p: 4.05, u: 'kg', v: true},
  'Riz basmati': {p: 4.02, u: 'kg', v: true},
  'Pâtes complètes': {p: 2.45, u: 'kg', v: false},
  'Flocons avoine': {p: 1.68, u: 'kg', v: true},
  'Lentilles corail': {p: 2.24, u: 'kg', v: false},
  'Lentilles vertes': {p: 3.31, u: 'kg', v: true},
  'Pois chiches': {p: 2.83, u: 'kg', v: true},
  'Haricots rouges': {p: 2.04, u: 'kg', v: false},
  'Quinoa': {p: 6.97, u: 'kg', v: true},
  'Semoule complète': {p: 2.55, u: 'kg', v: false},
  'Farine complète': {p: 1.02, u: 'kg', v: false},
  'Pain complet': {p: 2.83, u: 'kg', v: true},
  'Tortillas complètes': {p: 5.1, u: 'kg', v: false},
  'Courgette': {p: 2.24, u: 'kg', v: false},
  'Carotte': {p: 1.22, u: 'kg', v: false},
  'Poivron': {p: 3.06, u: 'kg', v: false},
  'Tomates': {p: 2.55, u: 'kg', v: false},
  'Tomates cerises': {p: 6.12, u: 'kg', v: false},
  'Tomates concassées': {p: 1.53, u: 'kg', v: false},
  'Épinards frais': {p: 3.06, u: 'kg', v: false},
  'Brocoli': {p: 2.55, u: 'kg', v: false},
  'Patate douce': {p: 2.24, u: 'kg', v: false},
  'Pomme de terre': {p: 1.53, u: 'kg', v: false},
  'Champignons': {p: 4.59, u: 'kg', v: false},
  'Salade verte': {p: 2.04, u: 'kg', v: false},
  'Oignon': {p: 1.02, u: 'kg', v: false},
  'Ail': {p: 5.1, u: 'kg', v: false},
  'Haricots verts': {p: 3.57, u: 'kg', v: false},
  'Poireaux': {p: 3.06, u: 'kg', v: false},
  'Courge butternut': {p: 2.55, u: 'kg', v: false},
  'Potiron': {p: 2.04, u: 'kg', v: false},
  'Aubergine': {p: 3.06, u: 'kg', v: false},
  'Avocat': {p: 3.06, u: 'kg', v: false},
  'Maïs': {p: 3.71, u: 'kg', v: true},
  'Fenouil': {p: 3.06, u: 'kg', v: false},
  'Asperges': {p: 6.12, u: 'kg', v: false},
  'Radis': {p: 3.57, u: 'kg', v: false},
  'Petits pois': {p: 3.57, u: 'kg', v: false},
  'Fèves': {p: 4.59, u: 'kg', v: false},
  'Roquette': {p: 8.16, u: 'kg', v: false},
  'Mâche': {p: 9.18, u: 'kg', v: false},
  'Endives': {p: 3.06, u: 'kg', v: false},
  'Céleri branche': {p: 2.55, u: 'kg', v: false},
  'Céleri-rave': {p: 2.24, u: 'kg', v: false},
  'Chou blanc': {p: 1.53, u: 'kg', v: false},
  'Chou vert': {p: 1.84, u: 'kg', v: false},
  'Chou rouge': {p: 2.04, u: 'kg', v: false},
  'Chou-fleur': {p: 2.55, u: 'kg', v: false},
  'Betterave': {p: 2.04, u: 'kg', v: false},
  'Châtaignes': {p: 6.63, u: 'kg', v: false},
  'Navets': {p: 1.84, u: 'kg', v: false},
  'Panais': {p: 3.06, u: 'kg', v: false},
  'Topinambours': {p: 3.57, u: 'kg', v: false},
  'Banane': {p: 1.53, u: 'kg', v: false},
  'Pomme': {p: 2.55, u: 'kg', v: false},
  'Poire': {p: 2.86, u: 'kg', v: false},
  'Kiwi': {p: 3.06, u: 'kg', v: false},
  'Fraises': {p: 4.08, u: 'kg', v: false},
  'Framboises': {p: 8.16, u: 'kg', v: false},
  'Myrtilles': {p: 12.24, u: 'kg', v: false},
  'Fruits rouges surgelés': {p: 8.16, u: 'kg', v: false},
  'Mangue': {p: 4.08, u: 'kg', v: false},
  'Pêche': {p: 3.57, u: 'kg', v: false},
  'Abricots frais': {p: 3.06, u: 'kg', v: false},
  'Abricots secs': {p: 12.24, u: 'kg', v: false},
  'Citron': {p: 2.04, u: 'kg', v: false},
  'Cerises': {p: 7.14, u: 'kg', v: false},
  'Rhubarbe': {p: 3.57, u: 'kg', v: false},
  'Nectarines': {p: 3.57, u: 'kg', v: false},
  'Pastèque': {p: 1.53, u: 'kg', v: false},
  'Melon': {p: 2.55, u: 'kg', v: false},
  'Prunes': {p: 3.06, u: 'kg', v: false},
  'Figues': {p: 6.12, u: 'kg', v: false},
  'Raisin': {p: 3.57, u: 'kg', v: false},
  'Coing': {p: 2.55, u: 'kg', v: false},
  'Kaki': {p: 4.08, u: 'kg', v: false},
  'Orange': {p: 2.04, u: 'kg', v: false},
  'Clémentine': {p: 2.55, u: 'kg', v: false},
  'Amandes': {p: 15.95, u: 'kg', v: true},
  'Noisettes': {p: 22.8, u: 'kg', v: true},
  'Noix': {p: 28.2, u: 'kg', v: true},
  'Beurre cacahuète': {p: 9.4, u: 'kg', v: true},
  'Graines de chia': {p: 8.16, u: 'kg', v: false},
  'Huile olive': {p: 6.12, u: 'L', v: false},
  'Chocolat noir 70%+': {p: 22.06, u: 'kg', v: true},
  'Miel': {p: 15.89, u: 'kg', v: true},
  'Tahini': {p: 9.18, u: 'kg', v: false},
  'Noix de coco râpée': {p: 8.16, u: 'kg', v: false},
  'Pépites chocolat noir': {p: 12.24, u: 'kg', v: false},
};
